In [1]:
import pandas as pd
import sqlite3
import sentencepiece as spm
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.nn.utils.rnn import pad_sequence
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.model_selection import train_test_split
from tqdm import tqdm
from torch.nn.utils.rnn import pack_padded_sequence
torch.manual_seed(112358)

In [2]:
conn=sqlite3.connect("../data/archive.sqlite3")
cursor=conn.cursor()
df=pd.read_sql_query("SELECT * FROM posts,post_tags where posts.thread_id=post_tags.thread_id",conn)

In [3]:
df

,id,thread_id,user_id,created_at,thanks_count,nothanks_count,raw_html,processed_html,is_first_post,source,thread_id,tag
0,1,24681373,167643,1.647281e+09,0,0,<div></div>On a board the following six vector...,On a board the following six vectors are writt...,1,https://artofproblemsolving.com/community/p246...,24681373,Vectors
1,1,24681373,167643,1.647281e+09,0,0,<div></div>On a board the following six vector...,On a board the following six vectors are writt...,1,https://artofproblemsolving.com/community/p246...,24681373,geometry
2,2,24681347,167643,1.647280e+09,0,0,"<div></div>Let <img src=""//latex.artofproblems...",Let $\Gamma_1$ and $\Gamma_2$ be two circles e...,1,https://artofproblemsolving.com/community/p246...,24681347,geometry
3,3,24681324,167643,1.647280e+09,0,0,"<div></div>Let <img src=""//latex.artofproblems...",Let $P_1P_2...P_n$ be a regular $n$-gon in the...,1,https://artofproblemsolving.com/community/p246...,24681324,combinatorics
4,3,24681324,167643,1.647280e+09,0,0,"<div></div>Let <img src=""//latex.artofproblems...",Let $P_1P_2...P_n$ be a regular $n$-gon in the...,1,https://artofproblemsolving.com/community/p246...,24681324,geometry
...,...,...,...,...,...,...,...,...,...,...,...,...
1174634,345979,1556697,148231,1.393553e+09,2,0,"<div></div><a href=""http://www.artofproblemsol...",Kyiv Taras Shevchenko University Mechmat Compe...,0,https://artofproblemsolving.com/community/p155...,1556697,inequalities
1174635,345979,1556697,148231,1.393553e+09,2,0,"<div></div><a href=""http://www.artofproblemsol...",Kyiv Taras Shevchenko University Mechmat Compe...,0,https://artofproblemsolving.com/community/p155...,1556697,inequalities unsolved
1174636,345980,1556697,148231,1.398564e+09,2,0,<div></div>The following inequality is also tr...,The following inequality is also true.\nShow t...,0,https://artofproblemsolving.com/community/p155...,1556697,algebra
1174637,345980,1556697,148231,1.398564e+09,2,0,<div></div>The following inequality is also tr...,The following inequality is also true.\nShow t...,0,https://artofproblemsolving.com/community/p155...,1556697,inequalities
1174638,345980,1556697,148231,1.398564e+09,2,0,<div></div>The following inequality is also tr...,The following inequality is also true.\nShow t...,0,https://artofproblemsolving.com/community/p155...,1556697,inequalities unsolved

In [4]:
df=df[df.is_first_post==1]
df

,id,thread_id,user_id,created_at,thanks_count,nothanks_count,raw_html,processed_html,is_first_post,source,thread_id,tag
0,1,24681373,167643,1.647281e+09,0,0,<div></div>On a board the following six vector...,On a board the following six vectors are writt...,1,https://artofproblemsolving.com/community/p246...,24681373,Vectors
1,1,24681373,167643,1.647281e+09,0,0,<div></div>On a board the following six vector...,On a board the following six vectors are writt...,1,https://artofproblemsolving.com/community/p246...,24681373,geometry
2,2,24681347,167643,1.647280e+09,0,0,"<div></div>Let <img src=""//latex.artofproblems...",Let $\Gamma_1$ and $\Gamma_2$ be two circles e...,1,https://artofproblemsolving.com/community/p246...,24681347,geometry
3,3,24681324,167643,1.647280e+09,0,0,"<div></div>Let <img src=""//latex.artofproblems...",Let $P_1P_2...P_n$ be a regular $n$-gon in the...,1,https://artofproblemsolving.com/community/p246...,24681324,combinatorics
4,3,24681324,167643,1.647280e+09,0,0,"<div></div>Let <img src=""//latex.artofproblems...",Let $P_1P_2...P_n$ be a regular $n$-gon in the...,1,https://artofproblemsolving.com/community/p246...,24681324,geometry
...,...,...,...,...,...,...,...,...,...,...,...,...
1174622,345975,1556712,46787,1.247242e+09,2,0,"<div></div>For each nonzero integer <img src=""...",For each nonzero integer $ n$ find all functio...,1,https://artofproblemsolving.com/community/p155...,1556712,algebra unsolved
1174623,345975,1556712,46787,1.247242e+09,2,0,"<div></div>For each nonzero integer <img src=""...",For each nonzero integer $ n$ find all functio...,1,https://artofproblemsolving.com/community/p155...,1556712,function
1174627,345977,1556697,46787,1.247241e+09,1,0,<div></div>Show that for all integers <span st...,"Show that for all integers $ n \ge 2$, $ \sqrt...",1,https://artofproblemsolving.com/community/p155...,1556697,algebra
1174628,345977,1556697,46787,1.247241e+09,1,0,<div></div>Show that for all integers <span st...,"Show that for all integers $ n \ge 2$, $ \sqrt...",1,https://artofproblemsolving.com/community/p155...,1556697,inequalities
1174629,345977,1556697,46787,1.247241e+09,1,0,<div></div>Show that for all integers <span st...,"Show that for all integers $ n \ge 2$, $ \sqrt...",1,https://artofproblemsolving.com/community/p155...,1556697,inequalities unsolved

In [5]:
df.memory_usage(deep=True)

Index               1346408
id                  1346408
thread_id           1346408
user_id             1346408
created_at          1346408
thanks_count        1346408
nothanks_count      1346408
raw_html          323690920
processed_html     73736543
is_first_post       1346408
source             16741166
thread_id           1346408
tag                10120919
dtype: int64

In [6]:
tag=df["tag"].value_counts()
tag

tag
geometry           19077
algebra            11493
number theory      11148
combinatorics      10196
inequalities        4823
                   ...
sets of numbers        1
Prove that             1
airlines               1
cities                 1
pco                    1
Name: count, Length: 3617, dtype: int64

In [7]:
# we 'll take the first 4
tag=tag[tag>10000]
tag

tag
geometry         19077
algebra          11493
number theory    11148
combinatorics    10196
Name: count, dtype: int64

In [8]:
df=df[df.tag.isin(tag.index)]

In [9]:
df

,id,thread_id,user_id,created_at,thanks_count,nothanks_count,raw_html,processed_html,is_first_post,source,thread_id,tag
1,1,24681373,167643,1.647281e+09,0,0,<div></div>On a board the following six vector...,On a board the following six vectors are writt...,1,https://artofproblemsolving.com/community/p246...,24681373,geometry
2,2,24681347,167643,1.647280e+09,0,0,"<div></div>Let <img src=""//latex.artofproblems...",Let $\Gamma_1$ and $\Gamma_2$ be two circles e...,1,https://artofproblemsolving.com/community/p246...,24681347,geometry
3,3,24681324,167643,1.647280e+09,0,0,"<div></div>Let <img src=""//latex.artofproblems...",Let $P_1P_2...P_n$ be a regular $n$-gon in the...,1,https://artofproblemsolving.com/community/p246...,24681324,combinatorics
4,3,24681324,167643,1.647280e+09,0,0,"<div></div>Let <img src=""//latex.artofproblems...",Let $P_1P_2...P_n$ be a regular $n$-gon in the...,1,https://artofproblemsolving.com/community/p246...,24681324,geometry
5,4,24681313,167643,1.647280e+09,0,0,"<div></div>Find, with proof, all functions <im...","Find, with proof, all functions $f : R - \{0\}...",1,https://artofproblemsolving.com/community/p246...,24681313,algebra
...,...,...,...,...,...,...,...,...,...,...,...,...
1174607,345970,1556755,46787,1.247244e+09,2,0,"<div></div>Consider a convex solid <img src=""/...",Consider a convex solid $ K$ in space and two ...,1,https://artofproblemsolving.com/community/p155...,1556755,geometry
1174610,345971,1556694,46787,1.247241e+09,1,0,<div></div>Determine the number of integers <i...,Determine the number of integers $ n$ with $ 1...,1,https://artofproblemsolving.com/community/p155...,1556694,number theory
1174615,345973,1556701,46787,1.247241e+09,2,0,<div></div>In a convex quadrilateral <span sty...,"In a convex quadrilateral $ ABCD$, let $ E$ be...",1,https://artofproblemsolving.com/community/p155...,1556701,geometry
1174621,345975,1556712,46787,1.247242e+09,2,0,"<div></div>For each nonzero integer <img src=""...",For each nonzero integer $ n$ find all functio...,1,https://artofproblemsolving.com/community/p155...,1556712,algebra
1174627,345977,1556697,46787,1.247241e+09,1,0,<div></div>Show that for all integers <span st...,"Show that for all integers $ n \ge 2$, $ \sqrt...",1,https://artofproblemsolving.com/community/p155...,1556697,algebra

In [10]:
ds=df.loc[:, ~df.columns.duplicated()].groupby("thread_id",as_index=True).agg(
    text=("processed_html","first"),
    tag=("tag",list)
)
ds

,text,tag
thread_id,,
2,"Let $ABC$ be a triangle, and $M$ an interior p...",[geometry]
3,okay this one is from Prof. Mircea Lascu from ...,"[algebra, geometry]"
5,"If A,B are invertible and the set {Ak - Bk | k...",[algebra]
9,In a magic square $n \times n$ composed from t...,"[algebra, combinatorics]"
72,The lengths of the sides of a convex hexagon $...,[geometry]
...,...,...
36238654,"Let $a, b, c$ be the altitudes of triangle $A$...",[geometry]
36238689,Find all functions that satisfy the condition ...,[algebra]
36238706,On an $N \times N$ “chessboard” ($N \ge 3$) ea...,[combinatorics]
36238733,It is known that $(20 + 25)^2 = 2025$. Find al...,[number theory]
36238754,"In triangle $ABC$, $AB &gt; AC$. Its inscribed...",[geometry]

In [11]:
ds.memory_usage(deep=True)

Index      371648
text     19470208
tag       3729424
dtype: int64

In [12]:
sp = spm.SentencePieceProcessor(model_file="my_tokenizer.model")

In [13]:
def tokenize(text):
    return sp.encode(text,out_type=int)
X=ds["text"].apply(tokenize)
X

thread_id
2           [215, 3, 427, 7916, 81, 6, 332, 7929, 35, 3, 7...
3           [4808, 232, 149, 275, 29, 264, 387, 7924, 7937...
5           [320, 79, 7929, 7951, 101, 7886, 35, 9, 439, 4...
9           [622, 6, 7885, 471, 3, 7914, 8, 705, 45, 7916,...
72          [266, 2315, 31, 9, 927, 31, 6, 2166, 3058, 3, ...
                                  ...
36238654    [215, 3, 7912, 7929, 24, 7929, 18, 7916, 81, 9...
36238689    [1022, 170, 1892, 38, 1023, 9, 733, 98, 170, 5...
36238706    [1782, 22, 3, 7967, 8, 705, 147, 7916, 7909, 0...
36238733    [533, 29, 1689, 38, 156, 1611, 68, 2514, 256, ...
36238754    [622, 332, 3, 427, 48, 3, 311, 138, 217, 7958,...
Name: text, Length: 46456, dtype: object

In [14]:
mlb = MultiLabelBinarizer()
Y = mlb.fit_transform(ds["tag"])
print(mlb.classes_)

['algebra' 'combinatorics' 'geometry' 'number theory']

In [15]:
class ContestProblemDataset(Dataset):
    def __init__(self, X, Y):
        self.X = [torch.tensor(x, dtype=torch.long) for x in X]   
        self.Y = torch.tensor(Y, dtype=torch.float32)              

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.Y[idx]

def collate_fn(batch):
    xs, ys = zip(*batch)
    x_lens = torch.tensor([len(x) for x in xs])
    x_padded = pad_sequence(list(xs), batch_first=True, padding_value=8000)
    y_batch = torch.stack(ys)   
    return x_padded, y_batch, x_lens

In [16]:
BATCH_SIZE=16

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.9,random_state=42)
X_val,X_test,Y_val,Y_test=train_test_split(X_test,Y_test,test_size=0.5,random_state=42)

train_ds=ContestProblemDataset(X_train,Y_train)
val_ds=ContestProblemDataset(X_val,Y_val)
test_ds=ContestProblemDataset(X_test,Y_test)

train_loader=DataLoader(train_ds,BATCH_SIZE,shuffle=True,collate_fn=collate_fn)
val_loader=DataLoader(val_ds,BATCH_SIZE,shuffle=False,collate_fn=collate_fn)
test_loader=DataLoader(test_ds,BATCH_SIZE,shuffle=False,collate_fn=collate_fn)

print(f"Train batches: {len(train_loader)}")
print(f"Validation batches: {len(val_loader)}")
print(f"Test batches: {len(test_loader)}")

Train batches: 291
Validation batches: 1307
Test batches: 1307

In [17]:
train_ds.X

[tensor([6758,   44,    9, 2527,    9,  585,    3, 5079,  782, 7922,  180, 3141,
         7944,  133,  786,  735,   42, 7944, 7937,    3,  336, 7913, 7976, 7967,
           80,  693, 4367,   92,   13,  537, 7913, 7976]),
 tensor([1022,  170,    9, 2398,    3, 7957, 7936, 7944,  109,   31,    6, 1465,
           43,  298,   45, 7916,  144,  566,  758, 7943, 1748, 2071,  230,   38,
            3, 7957, 7936, 7944, 7935,    8,  134,  145,  212,   34,  186, 7944,
          931,    8,  298,  336, 7957, 1047, 7976,  835,  468,    3,    8, 1101,
          166, 7964,  217, 2929]),
 tensor([ 280,  354,    7, 2103,  100,   80,    9,  855, 3288, 7937,  215,  305,
         5546, 5002,    3,    8,   34, 7927, 7917, 2493, 7911, 4682,   35,    3,
            8,   34, 7927, 7917, 3529, 7911, 5489,   81,  850,  159,   44, 4093,
         7917, 7929,  144,    9, 3341, 4812,   35, 6821, 1519,  380,  529, 7937,
          240, 7055,    3,   12,  570,   35,    3,   12,  699,  153, 1287, 3213,
         1453, 2184,    3,   18, 7916,   35, 1133,    3,    6,  570,   35,    3,
            6, 1838,  744, 7937, 5724, 7913,  152, 2995, 7929, 1522,    3,    4,
          570,   35,    3,    4,  699,  153, 1287, 3213, 1453, 2184,    3,   49,
         7916,   35, 1133,    3,   24,  570,   35,    3,   24, 1838,  744, 7937,
         2347,   38, 7929,  606,    6, 1765, 2593,    3,    8,   34, 7927, 7912,
           87, 7934,  129,   68,    6,  129, 7934, 2493, 7911,   87, 7934, 1336,
           48, 4821,  132, 7929,   35, 3272,    9, 3865,   31,    9,  893,  153,
            3,   18,   33,  280,  354,    7, 4828,   38,  149, 3288, 1233,  603,
         7917,    9,  493,   31,    9, 1527, 5002,  159,   22, 5546, 2593, 7937,
         2140, 2245,  601, 1526, 7991]),
 tensor([ 622,    6, 2166, 1227,    3, 1340,   48, 2329,    3,  378, 7916,   35,
            3,  890, 7916,  101,  491, 7937,  242, 1788, 1421, 2188, 1033,  144,
         3208,    3, 7977,  495, 7977,  837, 7977, 2300, 7977, 3000,   95,    9,
          927,  927,    3,  311, 7929,  676, 7929, 1542, 7929, 4667, 7916, 3278,
           31,  149, 1227, 7929,  744, 7937, 1730,   38,    3, 7977,   87, 7977,
          383,    8,  955,  323,  129, 7977, 6740]),
 tensor([ 215,    3, 7953,   87,  468,  120,  699,   81,  305, 1267,   44,    9,
         1649, 5144,  165,  305, 1051,  420, 7937,  215,    3, 7957, 7916,   81,
            9,  611,   31,    6, 2584, 2906,    3,  311, 7916,   31,    3, 7953,
          699,  144,    9, 2098,   38,    9,  419,   95,    3,  311, 7916,  159,
         1784, 2634,    3, 7953,  570,  165,    6,  189,    3, 7956, 7916,  230,
           38,    3, 7957,   74, 7916,   29,  669,   58,    3, 7953,  570,  754,
         1022,    9, 4118,   31,    3, 7957, 7916,  754]),
 tensor([  23, 2153,   79, 2082,   31,  321,  112,   20, 4423,  127,  983,  547,
           80,    6, 2990,   31, 4007, 2293, 7920,   56,  828, 7929,   35, 2858,
          840, 4176,   38,  695,  897,   31,  655,  127, 1158, 7930,  128, 1817,
         7929, 7297,  127,  731,   69, 6401, 1520,  432, 7917,   35,  498,  897,
          127,   19,  205,  146,  281, 7917, 7937,  512,  101,  984, 3073, 2293,
         7920,   56,  828,   38,  127, 1158, 7930,  128, 1817,   35,  731,   69,
         6401, 1520,  432, 7917, 7929, 3073,  144, 1158, 7930,  128, 1817,   35,
           19,  205,  146,  281, 1402, 7929,   35, 3073,  144,  731,   69, 6401,
         1520,  432, 7917,   35, 1158, 7930,  128,  146,  281, 7917, 7937,  703,
         2306, 1625, 2260, 7929,   31,  170, 2293, 7920,   56,  828, 7929,  381,
          305,  127,  170,  863,  848,  154, 7917,  165,    9,  483, 1266, 7929,
         1821,    9, 1152,  224, 1586, 2293, 7920,   56,  828,  840,  101,   44,
         1455,  733, 7937, 2421,  992,  898, 1260,   18, 2947,  101,   95,   38,
         2990, 7937,   23, 2754,   79,  244,   29, 2635,  336, 7913, 7976, 7924,
          749, 7924,   50,  241, 2123, 7913, 7976, 6784,  880,   35,  170,    9,
          362,   38,  101, 3251,  153, 5001,   63, 1287, 1417,   44,  331,  995,
          840,  101, 3564,   31, 5085, 2421,  992,  898, 2125,  812, 3363,  362,
          101, 1421, 7924,   50, 2099, 7937,  621, 7965,   79, 4251,  244, 1421,
         1188,  127, 1510, 1417,   44,  810, 4490, 3602, 7937,   23, 2320,   79,
          727,   31,  362,   29, 2816, 7929,  371,   31,  197,   29,  491,   58,
            9, 1496,   31, 1355, 1793,  362, 7929,  159,  684, 7965,  224,    8,
          705,   93,    8,  705, 2691,  210,    8,  705,  192,    8,  705, 3451,
          498,    8,  705,  289,    8,  705, 4603, 1200,  468,    3, 1176,    8,
          705,    0, 3639,    8,  705,   71,  875, 1011, 7926,   20, 6778,    9,
         7328,   31,  170,  655,  362,   35, 1133, 7917,  159,    6,  893,    6,
         1734,  244, 7929, 2193, 7864, 1950,   29,    3, 7931, 1512,  914, 7916,
           72, 4556,   29, 7929,    3, 7931, 7916,   35,    3, 7949, 7916,  127,
          608, 1985,   44, 1453,  188,  144, 1629,    3, 7931, 7916,   35,    3,
         7949,   33, 1022,    9,  750,   31,    3, 7931,   68,  914,   33,   23,
         1986,  512,   29,    6, 2430,    3, 1340, 7916,  144, 6860,    3,  583,
         7916,   35,    3,  171,   33,   79,  189,    3, 7972, 7916, 1564, 2388,
          775,    3,  311, 7916,   35,  356,    3, 7977, 1563,    3, 7977,  699,
           81,    9, 3208,   31,    9, 1267,   38, 1153,  730,    9,  861,   31,
            9, 1033,    3, 1058, 7961, 7916,   35,    3, 1461, 7953,   48,  744,
         7937, 1730,   38,    9, 1592,  264,    3, 7977,  570,   58,    3, 7977,
          699,   29, 1072, 7929, 6358,   31,    9, 2231,   31,  189,    3, 7972,
           33,   23, 2204, 2421,    9,  750,   31,    9,  855, 1950, 7965,  558,
          180,  994,   68,    8,  180,  994,   39,  105,  866,  328, 1771,  180,
         3413,   68,    8,  180, 3413,   39,  105,  866,  328,   68,    8,  180,
         4943,   68,    8,  180, 4943,   39,  105,  866,  328,  105,    8,  180,
          303, 7952,   68,    8,  180,  303, 7952,   39,  105,  866,  328,   68,
            8,  180,  303, 7968,   68,    8,  180,  303, 7968,   39,  105,  866,
          328,  105, 1200, 1848,  180, 1820, 1452,   68,    8,  180, 1820, 1452,
          536, 7968,  328,  896]),
 tensor([ 215,   81,    6, 1629,  244,    3,  214,    3,   35,  356,   81,  305,
         1248, 2704,    3,    8,  179, 7936,  166, 7942, 7914,    8,  125, 4697,
         7914, 7922,  122,  886, 4754,  179, 7936,  162, 7942, 7914,    8,  125,
         4697, 7914, 7922,  122,  886,    3,  230,   38,  216, 6697, 3579,  492,
         1568,  166,  495, 7944, 1882,  610,  468, 7944, 7942, 7950, 7105,  131,
         3579,  492, 1568,  162,  495, 7939, 1882,  610,  468, 7939, 7942, 7950,
         1298,   42, 1568,  166,  495, 7944, 1882,  610,  468, 7944, 7942, 7950,
         3579,  492, 1568,  162,  495, 7939, 1882,  610,  468, 7939, 7942, 7950,
         1298, 1617, 5161,  468,  216,  434, 2235,  153,    9,  855, 5100, 4654,
         7965,  216,  166,   64, 7914, 7941, 7950,  411,   34, 7927, 7939, 7942,
         7914,   36, 7944, 7942, 7914, 7928, 4754,  423,  162,   64, 7914, 7941,
         7950, 7928, 1617,   34, 7927, 7939, 7942, 7914, 1633, 7944, 7942, 7914,
          276,  216, 2762,   38,    3,    8,  179, 7936,  166, 7942, 7914,    8,
          125, 4697, 7914, 7922,  122,  886,    3,   35,    3,    8,  179, 7936,
          162, 7942, 7914,    8,  125, 4697, 7914, 7922,  122,  886,    3,  101,
         3500, 7937,  336, 7913, 7976, 7961,   65,   27,  630,   79, 4367,  537,
         7913, 7976]),
 tensor([2508,  153,    3, 7972, 7936, 7914,  109,    9,  244,   31, 7568, 7917,
           44,    9, 3624, 3602,   31,    6,  380,  451,    3, 7914,   33, 2843,
            3, 7914, 7916,  336, 7913, 7976, 6394, 2919,  537, 7913, 7976,  201,
            3, 7972, 7936, 7914,  109, 1513,    3, 7914,   33,  635,   38,   72,
         7912, 7935,  213, 1188,   81, 3232, 1793, 3717,  362, 7929,   35,   72,
         7934, 7935,  213,  101, 1807,  898,  380,  529,    3, 7914, 7916,  230,
           38,    3, 7914,   48,    3, 7914,  755,   35,    3, 7914, 2845,  101,
          371, 3717, 7937]),
 tensor([ 248,   30,  119, 6507, 3073, 1051,  380,  529,   35,  880, 5437,  170,
         3279,   43,  894, 2318, 7917,   35, 3279, 5023,  277,  103, 1697,   97,
         7963, 7917,   72, 7912, 1260,   31, 2285,  317,  362, 7935,   58,  280,
           61,  117, 7923, 7937, 2239,  280,   61,  117, 7923, 1233,  603,    9,
          519, 3073,  362, 7929,  597,  153, 7301,  655, 2285,  317,  362, 7991,
          336, 7913, 7976, 2148,  153,  280,   37,  114, 4609,  108, 7912,   90,
         3455, 2178, 2123, 7913, 7976]),
 tensor([ 215,    3, 7931, 7916,   81,    6,  541,   35,    3, 7957, 7922,    7,
            8,  358, 7927, 7982, 3303, 7944, 1307,   81,    6,  970,   31, 1465,
         1203,  504,    3, 7931,  660,  230,   38,   43, 5188,  145, 4554, 5422,
          115, 5188,  145,  262,  208, 5422,  115,  610,  115, 5188,  145, 7936,
         7931,  208, 5422,   33,  635,   38,    3, 7957, 7916,   29, 1072, 7937]),
 tensor([2421,    9,  529,    3, 7914, 7922, 2945, 1204,   98,  197,    9,  585,
            3, 7944, 4939, 1304, 6753,  134,  166,  176, 1304,  994,  411, 1304,
         7927, 3263,  376,    6, 1925,  254,   44, 1906,  358, 7927, 7992, 2119,
         7914, 7929, 7941,  287,  134, 2029]),
 tensor([1022,  170,    9,  380,  529,    3, 7912, 7929, 7934, 7929, 7921, 7916,
          230,   38,  498,  225, 7940,   93, 7921,  835,   35,    3, 7912, 1148,
         7934, 1148, 7921, 2982,   29,    9, 3486,   31,    6,  541,  244, 7937]),
 tensor([1143, 2613,   29,  839,  265, 7915, 3323,   98,   26,  630,   27, 7937,
         1378, 7910, 2876,  929,   38, 1421,  228, 7504, 7929,  863,   24,   20,
           20,   61,   35,  275,  146, 1128, 6881, 7917,  984,    9,  483,  159,
          863,  228, 7504,   35,  305,  146, 1128, 7917,   72,  710,  415,  591,
          101,   44, 3431,  214, 2856,   11,  333, 2998,  185, 3690, 4251,  116,
           25,  217,   18,   41,  267, 7929,   35, 1143, 2613, 4033,  149,   58,
         4740, 7937,  116,   25,  217,  905,  152, 1182, 7929,   38, 7909, 2444,
            7, 1692,  203,   29,  229, 1529,   98,  321,   58,  559,  992, 1987,
          371,   26,  630,   27, 6881, 7917, 2444, 7937, 7909, 2444, 4918, 7963,
         1268, 3803, 1143, 2613, 7929, 7963, 3290, 3301,  863,  228, 7504,   35,
          305,  146, 1128, 7917, 6881,  159,  898,  214, 2856,   11,  159, 1439,
           52, 1186,   29, 4007, 2444, 7937, 7424, 7929,  132, 7963, 7917,  229,
         1529, 1031, 7929,  402,  201, 2572, 1856, 2085,  325,  670,   11,  185,
            9, 4975,  789,  127, 2085, 1842,   98,  325,   58,   81, 3566,   58,
         2526,  839,  975,    9,   26,  630,  801, 6881, 7917, 7937,  900, 4007,
           29,  116,   25,  217, 7963, 7917,   52, 1186, 7991]),
 tensor([ 320,  498, 7912, 7116,  180, 2022,  975,   29,    9, 1762,  451,  229,
         4489,   63, 2285, 7912,  578, 2933, 7912, 1148, 7973, 7912, 7016, 7912,
         7941, 1449, 7991,    3,    8,  790,  463, 7948, 1015,  816,    8, 1004,
         7922,  790,  463, 7951, 1015,  866,    8, 1004, 7922,  790,  463, 7953,
         1015, 1044,    8, 1004, 7922,  790,  463, 7961, 1015, 1013,    8, 1004,
         7922,  790,  463, 7972, 1015,    8,  277, 7927, 7967,  400,   31,    9,
         1063, 1401,   63, 7928,    3]),
 tensor([ 512,   29,    6,   58, 4947,   44,  275,   31,    9,   45, 5902,   31,
            6, 3058,  144,  775,    3, 7914,   48, 2778,  826, 2850, 1033,   72,
         5759, 2526,  333, 4188, 3365,  877, 3016, 3981,  132,   58,  275,   31,
            9, 2641, 4518,   45, 5902, 7929,   35,  132,   29,   98, 7934, 1538,
           58,  711,   58,    6, 7664,   38,    9,   58, 4947,  376, 2019, 4429,
         4379, 7937,  266,  275, 1606, 5816, 1606,  158, 7963, 7911, 1259,    6,
         1320, 7937,  781, 7915, 2667,  144,    9,  800, 2331, 7991, 1704, 1149,
         3518, 7937,  354, 1781, 7937,  779, 7980, 3825,  691, 7980, 7924, 7980,
         1394, 6751, 5154, 7974, 7924, 7968, 7924, 7955,  628, 7973, 7910, 2018,
         1609, 1623, 7912, 7973, 7910, 7962, 1163, 7933, 7910, 1473, 7924, 7955,
         7910, 7932, 1080, 7937, 2830]),
 tensor([1782,    9, 1294,    3,  729, 7929,  171, 7929,  857, 7929, 2048, 7916,
           31,    6, 1792,   10,  473, 7931,   80,    3,  723, 2048,   87,  116,
           87,  120,   87,  240,  570,  420,    3,  743, 7929, 7971, 7929, 7970,
         7929, 7967, 7916,  101, 4749, 7929,  744, 7937,  635,   38,    9, 6830,
           31,    9, 4092, 3040,   21,    3,   79,   87, 3377, 7967, 7929,  116,
           87,  116, 2361, 7929,  120,   87,  120, 5358, 7929,  240,   87,  240,
         1495, 7916,  101,  861,   31,    6, 1872, 7937]),
 tensor([1022,  170, 3456,  156, 7931, 7929, 7949, 7929, 7914,  109,   38, 1023,
          258, 7949,   76, 7914, 1090,    8,  263, 3955, 7914, 1090, 1043,  295,
           23, 7945, 7914, 7935, 4754,  423,   23,   76, 7914, 1090,    8,  263,
         3955, 7914, 1090, 1043,  295,  914, 7945, 7914, 1737,  445,    3, 7931,
         7929, 7949, 7916,  101,  556, 1372,   35,    3, 7914, 7916,   29,   22,
          380,  451, 7937]),
 tensor([ 215,    6,  332,    3,  427, 7916, 2793,   44,  419,    3, 7921, 7936,
         7977, 7929, 7982,  109,   35,    3, 7961, 7916,   22, 2259,  189,   95,
            3,  171, 3637, 7923, 6902,  264,    9,  611,  333,  815, 4732,  419,
           31,    3, 3214, 7961,   48, 1136,   29,  156, 7921,   87,  453, 2634,
            3, 7921, 7936, 7977, 7929, 7982,  109,  165,    3, 7988, 7916,   35,
            3,  311, 7916,  165,    3, 7992,   33,  815, 4732,  419,   31,    3,
         7953, 3646, 7916,  156, 7921, 7861,   99, 4143,    3, 7921, 7936, 7977,
         7929, 7982,  109,  165,    3, 7970, 7916,   35,    3,  378, 7916,  165,
            3, 7972,   33, 7415, 7929,    9, 4732,  419,   31,    3, 1058, 7992,
         7916,  156, 7921,  383,  453,   99, 4143,    3, 7921, 7936, 7977, 7929,
         7982,  109,  165,    3, 7967,   33, 2762,   38,   43,  312, 7927,  427,
          411,  312, 7927, 7988, 1495, 1903]),
 tensor([ 622,    9, 1227,    3, 1340,   48,   62,  127,    3,  311,   42, 1187,
         7916,   35,   43,   54,  116,   42,    8,   54,  240,   42, 1028, 3131,
            8,  409, 1801,  266,  420,    3, 7957, 7916,   35,    3, 7986,    3,
         1329,   95,    3,  171, 7916,   35,    3,  857,   48,  744, 7929,   73,
           38,    3, 1650, 7916,   29,  845,   95,    3, 2805,   33,  635,   38,
            3, 1005, 7916,   29,  845,   58,    3, 2428,   33]),
 tensor([1022,    9, 2774,  136, 1152, 1738,  264,    9,  800,   31,    9, 4490,
         3602,   31, 2081, 6619, 6619, 6619, 6619, 2050,  328, 3828,  336, 7913,
         7976, 2148,  153,  145, 7913,  248,   20,  648, 4814,  537, 7913, 7976]),
 tensor([ 512,  101,  305, 1267,   31, 3398,  224, 1452, 4049,  215,  224, 1452,
         1449,  420,   81, 3799,   95,    9,  519,  419, 7929,   35, 4612, 3719,
          144,    9, 1260,  846,   31,  851,   95,    9,  867, 7937, 1730,   38,
          132,   29,  688,   58, 2175,    9,  867,  419, 2731,    9,  519,   44,
          230,    6,  956,   38, 2657,   31,    9, 3799,  420,   29, 4302,  153,
            6, 3799, 1356, 7937]),
 tensor([4188,  973,    3, 7925, 7916,   35,    3, 7914, 7916,  467,   44,    6,
         1925,  189,    3, 7957,   33,   79,  189,    3, 7970, 7916, 1564, 2388,
            3, 7925, 7916,  144, 1072, 5304, 7929, 1821, 1501,  189,    3, 7967,
         7916, 1564, 2388,    3, 7914, 7916,  144,    9,  483, 5304, 7937, 4220,
          647, 1153,  730,    9,  189,    3, 7957,   48,  402,  229,  165,    9,
          483, 1266, 7937, 1730,   38,  213,   29,    6, 1413,  189,    3, 7986,
            8,  489,  145, 7916,  230,   38,    9,  420,    3, 7957, 7929, 7986,
         7929, 7970, 7916,   35,    3, 7967, 7916, 1329,   95,    6, 1453,  419,
          170,    9, 1266, 7937]),
 tensor([  23, 2153,   79,  284,  164,   29, 2433,  925,  863, 5474,   83, 1189,
         7965,    3,   79,   48,    3,  116, 7916,   35,    3, 7953,   48,  144,
           22,  731,   69,   37,  412,   31, 5408, 1814, 7937, 2654,  731,   69,
           37,  284,   28,   30,   44,  995,   98,    9,  863, 5474,   83, 1189,
         7929,  371,  688, 5367, 5423, 6976,  165,  590,  275,  284,  164, 7937,
         4312,    9,  284,   28,  135, 7929, 5254, 1063, 6307,  247,    3,   79,
         7916,  966,    3, 7951, 7916,   35,    3, 6064, 1063, 6307,  247,    3,
         7953, 7916,  966,    3,   79,   33, 2415,  149, 7929,    9,  731,   69,
         7915,  384, 5927,   14,  986, 6077,    3,  116, 7916,   58,  144, 2943,
           58, 1259,   22,  731,  299,  381,  925,    3, 7948, 7916,   35,    3,
         7953,   33,  183,  746,   80,  144,  149, 1685,  502, 7929,    9, 5474,
           83,  412,    3, 7951, 7916, 2977,   28, 6170,   35, 1830,  715,   38,
          213,  101,  224, 1702,  284,   28,  135, 1606, 1063, 6307, 4740,  966,
            3, 7953,   33, 2415,    9, 1492,   75,   53, 7929,    9, 5927,   14,
          986,  318, 1682, 7915,  384, 1463,  612,   58, 1259,   22,  731,  299,
          925,    9,  519,  305, 1762,    6,   91, 7937, 2421,  197,   31,    9,
         5474,   83, 1189,  101,    9, 2509, 1606, 1410,    9,  519, 5636,    6,
           91, 7929,   35,  992,  898,  284,   28,   30, 1029,  840,  246, 7937,
           23, 2754,  557,  371,  380,  451,    3, 7914,   48,  430,   38,    3,
         7914,   39,   68,   45,   68,  659,   29,  229,    6, 1455,  471, 7937,
           23, 2320, 1022,  170,  451,  802,   31,    9,  585,    3, 7944,  260,
           68,   93, 7939,  260,   42,  289, 7978, 2982,   23, 1986,   43, 4228,
          723, 7916,  376,    6, 1120,    3, 7988,   33,  266, 3086, 2713,   31,
            9,  332,  467, 1134,    3, 7988, 7916,  165,    3, 7961,   48,    3,
         7972,   48,    3, 7969,   33,   43, 4228, 3862, 7916, 3016,  839,   58,
           81, 2188, 7937,  635,   38,   43, 4228,  723, 7916,   29, 2188, 7937,
           23, 2204,  215,    3, 7914, 7922,  122, 1204,   81,    6, 1629, 7937,
         2854,   10,  166, 1478,   10,  166, 1658,   10, 1200,    8,   10,  166,
         7942, 7914, 7916,  101,  566, 7929,  197,  127,  493,    3, 1100,  320,
            3, 7944, 7942, 7914,    8,   10,    8,   34, 3188,   48,  430,   38,
          213,  742,    3, 7950,   48,  144, 1969,   10,  214, 7922,   10,   45,
           48,  230,   38,  558,   34, 1198,    8,   10,    8,  187,   64, 7985,
           42, 4013, 7950, 7928,  166, 7942, 7985,    8,   10,    8,   34, 3188,
          198,   23, 2159,  215,    3, 7931, 7929,  914, 7929,  345, 7916,  529,
         7929,  445,    3,  345, 7916,   29,  229,    6, 1455,  471, 7937,  917,
           38,    3, 7944,   42,    8,  180, 3141, 7931, 1848,  180, 7927, 7918,
          328,   68,    8,  180, 3141, 7949, 1771,  180, 7927, 7918, 1597,   29,
            6, 1734, 7937,  635,   38,    3, 7931,   42,  914,   33,   23, 2356,
         1209,    6,  419,    3, 7953,   48,  144,  827,    3, 7977, 7916,   35,
         1480,    3, 7918, 7964,  217, 7958, 1318,  215,    3, 7986, 7916,   81,
            6,  189,   44,    9, 3086,   31,    3, 7953,   33,   79,  189,    3,
         7957,    8,    7,  120, 7916,   29, 3220,  159,  934,  159,    9,   43,
           54,  323,  907, 7916,  754, 5777, 1147,  189,    3, 7957, 7916, 1329,
          230,   38,    9,   43,   54,  323,  907, 7916,  376, 1404, 4960, 7991]),
 tensor([  72, 7913, 7935,    3,  427, 7916,   29,    6,  332,  144,    6,  800,
          569,  165,    3, 7948,   48,   35,    3, 7957, 7916,   29,    6,  189,
           95,    9, 5621,    3,  171,   33,  266,  367,    3, 1005, 7916, 1346,
         1401, 7806,    3, 7957, 7916, 2634,    9,  367,  730,    3, 7951, 7916,

In [18]:
class CateogoryLSTM(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim, n_layers, dropout, padding_idx):
        super().__init__()
        self.embedding=nn.Embedding(vocab_size,embedding_dim,padding_idx)
        self.LSTM=nn.LSTM(embedding_dim,hidden_dim,num_layers=n_layers,bidirectional=True,dropout=dropout,batch_first=True)
        self.dropout=nn.Dropout(dropout)
        self.fc=nn.Linear(2*hidden_dim,output_dim)
    def forward(self, text_batch, x_lens):
        embedded = self.embedding(text_batch)
        
        packed = pack_padded_sequence(embedded, x_lens.cpu(), batch_first=True, enforce_sorted=False)
        packed_out, (hidden, cell) = self.LSTM(packed)
        
        # hidden shape: [num_layers * num_directions, batch, hidden_dim]
        bi_hidden = torch.cat((hidden[-2, :, :], hidden[-1, :, :]), dim=1)
        
        dropped_out = self.dropout(bi_hidden)
        linear_out = self.fc(dropped_out)
        
        return linear_out

EMBEDDING_DIM = 100
HIDDEN_DIM = 256
OUTPUT_DIM = 4
N_LAYERS = 2
DROPOUT = 0.5
PADDING_IDX = 8000

# Instantiate the model
model = CateogoryLSTM(8001, 
                        EMBEDDING_DIM, 
                        HIDDEN_DIM, 
                        OUTPUT_DIM, 
                        N_LAYERS, 
                        DROPOUT, 
                        PADDING_IDX)

print(model)

CateogoryLSTM(
  (embedding): Embedding(8001, 100, padding_idx=8000)
  (LSTM): LSTM(100, 256, num_layers=2, batch_first=True, dropout=0.5, bidirectional=True)
  (dropout): Dropout(p=0.5, inplace=False)
  (fc): Linear(in_features=512, out_features=4, bias=True)
)

In [21]:
# --- Training Hyperparameters ---
LEARNING_RATE = 0.001
N_EPOCHS = 5
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Training on device: {device}")
criterion=nn.BCEWithLogitsLoss()
optimizer=optim.Adam(model.parameters(),lr=LEARNING_RATE)

model=model.to(device)
criteron=criterion.to(device)


def jaccard_accuracy(y_true, logits, threshold=0.5):
    probs = torch.sigmoid(logits)
    y_pred_bin = (probs > threshold).float()
    
    intersection = (y_true * y_pred_bin).sum(dim=1)
    union = ((y_true + y_pred_bin) > 0).float().sum(dim=1)
    jaccard = torch.where(union > 0, intersection / union, torch.ones_like(union))
    return jaccard.mean()

Training on device: cpu

In [ ]:


for epoch in range(N_EPOCHS):
    
    train_loss = 0.0
    train_acc = 0.0
    
    # --- Training Phase ---
    model.train() # Set model to training mode
    
    for inputs, labels,x_len in tqdm(train_loader, desc=f"Epoch {epoch+1}/{N_EPOCHS} [Train]"):
        inputs, labels = inputs.to(device), labels.to(device)
        
        # 1. Zero gradients
        optimizer.zero_grad()
        
        # 2. Forward pass
        predictions = model(inputs,x_len)
        
        # 3. Calculate loss and accuracy
        loss = criterion(predictions, labels)
        acc = jaccard_accuracy(labels,predictions)
        
        # 4. Backward pass
        loss.backward()
        
        # 5. Update weights
        optimizer.step()
        
        train_loss += loss.item()
        train_acc += acc.item()

Training on device: cpu

Epoch 1/5 [Train]: 100%|██████████| 291/291 [05:54<00:00,  1.22s/it]
Epoch 2/5 [Train]: 100%|██████████| 291/291 [05:15<00:00,  1.09s/it]
Epoch 3/5 [Train]: 100%|██████████| 291/291 [05:02<00:00,  1.04s/it]
Epoch 4/5 [Train]: 100%|██████████| 291/291 [05:21<00:00,  1.10s/it]
Epoch 5/5 [Train]: 100%|██████████| 291/291 [06:19<00:00,  1.30s/it]

In [19]:
# torch.save(model.state_dict(),"weight.model")
model.load_state_dict(torch.load("weight.model"))

model

CateogoryLSTM(
  (embedding): Embedding(8001, 100, padding_idx=8000)
  (LSTM): LSTM(100, 256, num_layers=2, batch_first=True, dropout=0.5, bidirectional=True)
  (dropout): Dropout(p=0.5, inplace=False)
  (fc): Linear(in_features=512, out_features=4, bias=True)
)

In [ ]:
model.eval()
text="""Let $\mathbb{N}$ denote the set of positive integers. A function $f\colon\mathbb{N}\to\mathbb{N}$ is said to be bonza if
\[
f(a)~~\text{divides}~~b^a-f(b)^{f(a)}
\]for all positive integers $a$ and $b$.

Determine the smallest real constant $c$ such that $f(n)\leqslant cn$ for all bonza functions $f$ and all positive integers $n$."""
tokens = sp.encode(text, out_type=int)
inp = torch.tensor(tokens).unsqueeze(0).to(device)
x_lens = torch.tensor([len(tokens)])  

with torch.no_grad():
    prediction = model(inp, x_lens)
    probs = torch.sigmoid(prediction)
    predicted_labels = (probs > 0.5).int()
    predicted_indices = torch.nonzero(predicted_labels.squeeze()).flatten().tolist()
    predicted_names = [mlb.classes_[i] for i in predicted_indices]
    print(predicted_names)  # ví dụ: ['algebra', 'geometry']

['number theory']

<>:2: SyntaxWarning: invalid escape sequence '\m'
<>:2: SyntaxWarning: invalid escape sequence '\m'
C:\Users\huyho\AppData\Local\Temp\ipykernel_2196\2942980154.py:2: SyntaxWarning: invalid escape sequence '\m'
  text="""Let $\mathbb{N}$ denote the set of positive integers. A function $f\colon\mathbb{N}\to\mathbb{N}$ is said to be bonza if