In [1]:
import sqlite3

import pandas as pd
import sentencepiece as spm
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MultiLabelBinarizer
from torch.nn.utils.rnn import pack_padded_sequence, pad_sequence
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm

In [2]:
conn = sqlite3.connect("../data/archive.sqlite3")
cursor = conn.cursor()
df = pd.read_sql_query(
    "SELECT * FROM posts,post_tags where posts.thread_id=post_tags.thread_id", conn
)

In [3]:
df

,id,thread_id,user_id,created_at,thanks_count,nothanks_count,raw_html,processed_html,is_first_post,source,thread_id,tag
0,1,24681373,167643,1.647281e+09,0,0,<div></div>On a board the following six vector...,On a board the following six vectors are writt...,1,https://artofproblemsolving.com/community/p246...,24681373,Vectors
1,1,24681373,167643,1.647281e+09,0,0,<div></div>On a board the following six vector...,On a board the following six vectors are writt...,1,https://artofproblemsolving.com/community/p246...,24681373,geometry
2,2,24681347,167643,1.647280e+09,0,0,"<div></div>Let <img src=""//latex.artofproblems...",Let $\Gamma_1$ and $\Gamma_2$ be two circles e...,1,https://artofproblemsolving.com/community/p246...,24681347,geometry
3,3,24681324,167643,1.647280e+09,0,0,"<div></div>Let <img src=""//latex.artofproblems...",Let $P_1P_2...P_n$ be a regular $n$-gon in the...,1,https://artofproblemsolving.com/community/p246...,24681324,combinatorics
4,3,24681324,167643,1.647280e+09,0,0,"<div></div>Let <img src=""//latex.artofproblems...",Let $P_1P_2...P_n$ be a regular $n$-gon in the...,1,https://artofproblemsolving.com/community/p246...,24681324,geometry
...,...,...,...,...,...,...,...,...,...,...,...,...
1174634,345979,1556697,148231,1.393553e+09,2,0,"<div></div><a href=""http://www.artofproblemsol...",Kyiv Taras Shevchenko University Mechmat Compe...,0,https://artofproblemsolving.com/community/p155...,1556697,inequalities
1174635,345979,1556697,148231,1.393553e+09,2,0,"<div></div><a href=""http://www.artofproblemsol...",Kyiv Taras Shevchenko University Mechmat Compe...,0,https://artofproblemsolving.com/community/p155...,1556697,inequalities unsolved
1174636,345980,1556697,148231,1.398564e+09,2,0,<div></div>The following inequality is also tr...,The following inequality is also true.\nShow t...,0,https://artofproblemsolving.com/community/p155...,1556697,algebra
1174637,345980,1556697,148231,1.398564e+09,2,0,<div></div>The following inequality is also tr...,The following inequality is also true.\nShow t...,0,https://artofproblemsolving.com/community/p155...,1556697,inequalities
1174638,345980,1556697,148231,1.398564e+09,2,0,<div></div>The following inequality is also tr...,The following inequality is also true.\nShow t...,0,https://artofproblemsolving.com/community/p155...,1556697,inequalities unsolved

In [4]:
df = df[df.is_first_post == 1]
df

,id,thread_id,user_id,created_at,thanks_count,nothanks_count,raw_html,processed_html,is_first_post,source,thread_id,tag
0,1,24681373,167643,1.647281e+09,0,0,<div></div>On a board the following six vector...,On a board the following six vectors are writt...,1,https://artofproblemsolving.com/community/p246...,24681373,Vectors
1,1,24681373,167643,1.647281e+09,0,0,<div></div>On a board the following six vector...,On a board the following six vectors are writt...,1,https://artofproblemsolving.com/community/p246...,24681373,geometry
2,2,24681347,167643,1.647280e+09,0,0,"<div></div>Let <img src=""//latex.artofproblems...",Let $\Gamma_1$ and $\Gamma_2$ be two circles e...,1,https://artofproblemsolving.com/community/p246...,24681347,geometry
3,3,24681324,167643,1.647280e+09,0,0,"<div></div>Let <img src=""//latex.artofproblems...",Let $P_1P_2...P_n$ be a regular $n$-gon in the...,1,https://artofproblemsolving.com/community/p246...,24681324,combinatorics
4,3,24681324,167643,1.647280e+09,0,0,"<div></div>Let <img src=""//latex.artofproblems...",Let $P_1P_2...P_n$ be a regular $n$-gon in the...,1,https://artofproblemsolving.com/community/p246...,24681324,geometry
...,...,...,...,...,...,...,...,...,...,...,...,...
1174622,345975,1556712,46787,1.247242e+09,2,0,"<div></div>For each nonzero integer <img src=""...",For each nonzero integer $ n$ find all functio...,1,https://artofproblemsolving.com/community/p155...,1556712,algebra unsolved
1174623,345975,1556712,46787,1.247242e+09,2,0,"<div></div>For each nonzero integer <img src=""...",For each nonzero integer $ n$ find all functio...,1,https://artofproblemsolving.com/community/p155...,1556712,function
1174627,345977,1556697,46787,1.247241e+09,1,0,<div></div>Show that for all integers <span st...,"Show that for all integers $ n \ge 2$, $ \sqrt...",1,https://artofproblemsolving.com/community/p155...,1556697,algebra
1174628,345977,1556697,46787,1.247241e+09,1,0,<div></div>Show that for all integers <span st...,"Show that for all integers $ n \ge 2$, $ \sqrt...",1,https://artofproblemsolving.com/community/p155...,1556697,inequalities
1174629,345977,1556697,46787,1.247241e+09,1,0,<div></div>Show that for all integers <span st...,"Show that for all integers $ n \ge 2$, $ \sqrt...",1,https://artofproblemsolving.com/community/p155...,1556697,inequalities unsolved

In [5]:
df.memory_usage(deep=True)

Index               1346408
id                  1346408
thread_id           1346408
user_id             1346408
created_at          1346408
thanks_count        1346408
nothanks_count      1346408
raw_html          291325751
processed_html     60677999
is_first_post       1346408
source              9861863
thread_id           1346408
tag                 3241616
dtype: int64

In [6]:
tag = df["tag"].value_counts()
tag

tag
geometry           19077
algebra            11493
number theory      11148
combinatorics      10196
inequalities        4823
                   ...
sets of numbers        1
Prove that             1
airlines               1
cities                 1
pco                    1
Name: count, Length: 3617, dtype: int64

In [7]:
# we 'll take the first 4
tag = tag[tag > 10000]
tag

tag
geometry         19077
algebra          11493
number theory    11148
combinatorics    10196
Name: count, dtype: int64

In [8]:
df = df[df.tag.isin(tag.index)]

In [9]:
df

,id,thread_id,user_id,created_at,thanks_count,nothanks_count,raw_html,processed_html,is_first_post,source,thread_id,tag
1,1,24681373,167643,1.647281e+09,0,0,<div></div>On a board the following six vector...,On a board the following six vectors are writt...,1,https://artofproblemsolving.com/community/p246...,24681373,geometry
2,2,24681347,167643,1.647280e+09,0,0,"<div></div>Let <img src=""//latex.artofproblems...",Let $\Gamma_1$ and $\Gamma_2$ be two circles e...,1,https://artofproblemsolving.com/community/p246...,24681347,geometry
3,3,24681324,167643,1.647280e+09,0,0,"<div></div>Let <img src=""//latex.artofproblems...",Let $P_1P_2...P_n$ be a regular $n$-gon in the...,1,https://artofproblemsolving.com/community/p246...,24681324,combinatorics
4,3,24681324,167643,1.647280e+09,0,0,"<div></div>Let <img src=""//latex.artofproblems...",Let $P_1P_2...P_n$ be a regular $n$-gon in the...,1,https://artofproblemsolving.com/community/p246...,24681324,geometry
5,4,24681313,167643,1.647280e+09,0,0,"<div></div>Find, with proof, all functions <im...","Find, with proof, all functions $f : R - \{0\}...",1,https://artofproblemsolving.com/community/p246...,24681313,algebra
...,...,...,...,...,...,...,...,...,...,...,...,...
1174607,345970,1556755,46787,1.247244e+09,2,0,"<div></div>Consider a convex solid <img src=""/...",Consider a convex solid $ K$ in space and two ...,1,https://artofproblemsolving.com/community/p155...,1556755,geometry
1174610,345971,1556694,46787,1.247241e+09,1,0,<div></div>Determine the number of integers <i...,Determine the number of integers $ n$ with $ 1...,1,https://artofproblemsolving.com/community/p155...,1556694,number theory
1174615,345973,1556701,46787,1.247241e+09,2,0,<div></div>In a convex quadrilateral <span sty...,"In a convex quadrilateral $ ABCD$, let $ E$ be...",1,https://artofproblemsolving.com/community/p155...,1556701,geometry
1174621,345975,1556712,46787,1.247242e+09,2,0,"<div></div>For each nonzero integer <img src=""...",For each nonzero integer $ n$ find all functio...,1,https://artofproblemsolving.com/community/p155...,1556712,algebra
1174627,345977,1556697,46787,1.247241e+09,1,0,<div></div>Show that for all integers <span st...,"Show that for all integers $ n \ge 2$, $ \sqrt...",1,https://artofproblemsolving.com/community/p155...,1556697,algebra

In [10]:
ds = (
    df.loc[:, ~df.columns.duplicated()]
    .groupby("thread_id", as_index=True)
    .agg(text=("processed_html", "first"), tag=("tag", list))
)
ds

,text,tag
thread_id,,
2,"Let $ABC$ be a triangle, and $M$ an interior p...",[geometry]
3,okay this one is from Prof. Mircea Lascu from ...,"[algebra, geometry]"
5,"If A,B are invertible and the set {Ak - Bk | k...",[algebra]
9,In a magic square $n \times n$ composed from t...,"[algebra, combinatorics]"
72,The lengths of the sides of a convex hexagon $...,[geometry]
...,...,...
36238654,"Let $a, b, c$ be the altitudes of triangle $A$...",[geometry]
36238689,Find all functions that satisfy the condition ...,[algebra]
36238706,On an $N \times N$ “chessboard” ($N \ge 3$) ea...,[combinatorics]
36238733,It is known that $(20 + 25)^2 = 2025$. Find al...,[number theory]
36238754,"In triangle $ABC$, $AB &gt; AC$. Its inscribed...",[geometry]

In [11]:
ds.to_csv("out.csv")

In [12]:
ds.memory_usage(deep=True)

Index      371648
text     16118975
tag       3729424
dtype: int64

In [13]:
sp = spm.SentencePieceProcessor(model_file="my_tokenizer.model")

In [14]:
def tokenize(text):
    return sp.encode(text, out_type=int)


X = ds["text"].apply(tokenize)
X

thread_id
2           [215, 3, 427, 7916, 81, 6, 332, 7929, 35, 3, 7...
3           [4808, 232, 149, 275, 29, 264, 387, 7924, 7937...
5           [320, 79, 7929, 7951, 101, 7886, 35, 9, 439, 4...
9           [622, 6, 7885, 471, 3, 7914, 8, 705, 45, 7916,...
72          [266, 2315, 31, 9, 927, 31, 6, 2166, 3058, 3, ...
                                  ...
36238654    [215, 3, 7912, 7929, 24, 7929, 18, 7916, 81, 9...
36238689    [1022, 170, 1892, 38, 1023, 9, 733, 98, 170, 5...
36238706    [1782, 22, 3, 7967, 8, 705, 147, 7916, 7909, 0...
36238733    [533, 29, 1689, 38, 156, 1611, 68, 2514, 256, ...
36238754    [622, 332, 3, 427, 48, 3, 311, 138, 217, 7958,...
Name: text, Length: 46456, dtype: object

In [15]:
mlb = MultiLabelBinarizer()
Y = mlb.fit_transform(ds["tag"])
print(mlb.classes_)

['algebra' 'combinatorics' 'geometry' 'number theory']

In [16]:
class ContestProblemDataset(Dataset):
    def __init__(self, X, Y):
        self.X = [torch.tensor(x, dtype=torch.long) for x in X]
        self.Y = torch.tensor(Y, dtype=torch.float32)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.Y[idx]


def collate_fn(batch):
    xs, ys = zip(*batch)
    x_lens = torch.tensor([len(x) for x in xs])
    x_padded = pad_sequence(list(xs), batch_first=True, padding_value=8000)
    y_batch = torch.stack(ys)
    return x_padded, y_batch, x_lens

In [17]:
X=X.apply(lambda ids: " ".join(map(str, ids)))

In [18]:
BATCH_SIZE = 16

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.3, random_state=42
)
X_val, X_test, Y_val, Y_test = train_test_split(
    X_test, Y_test, test_size=0.5, random_state=42
)

# train_ds = ContestProblemDataset(X_train, Y_train)
# val_ds = ContestProblemDataset(X_val, Y_val)
# test_ds = ContestProblemDataset(X_test, Y_test)

# train_loader = DataLoader(train_ds, BATCH_SIZE, shuffle=True, collate_fn=collate_fn)
# val_loader = DataLoader(val_ds, BATCH_SIZE, shuffle=False, collate_fn=collate_fn)
# test_loader = DataLoader(test_ds, BATCH_SIZE, shuffle=False, collate_fn=collate_fn)

# print(f"Train batches: {len(train_loader)}")
# print(f"Validation batches: {len(val_loader)}")
# print(f"Test batches: {len(test_loader)}")

In [19]:
X

thread_id
2           215 3 427 7916 81 6 332 7929 35 3 7970 7916 22...
3           4808 232 149 275 29 264 387 7924 7937 280 94 9...
5           320 79 7929 7951 101 7886 35 9 439 426 7948 79...
9           622 6 7885 471 3 7914 8 705 45 7916 905 2727 2...
72          266 2315 31 9 927 31 6 2166 3058 3 723 3147 79...
                                  ...
36238654    215 3 7912 7929 24 7929 18 7916 81 9 3551 31 3...
36238689    1022 170 1892 38 1023 9 733 98 170 566 362 3 7...
36238706    1782 22 3 7967 8 705 147 7916 7909 0 112 1687 ...
36238733    533 29 1689 38 156 1611 68 2514 256 42 1835 38...
36238754    622 332 3 427 48 3 311 138 217 7958 768 33 629...
Name: text, Length: 46456, dtype: str

In [20]:
X_train

thread_id
21183769    74 25 4440 4482 7929 371 31 846 2355 101 3520 ...
1428739     557 6 1628 439 3 553 7916 31 380 529 7929 356 ...
2165298     242 101 850 3 7914 8 282 1636 4859 31 4678 30 ...
21704410    1022 9 244 31 1734 802 31 9 855 1833 72 7913 7...
7595519     1022 9 1427 863 7943 3363 2184 31 9 244 258 20...
                                  ...
3553773     557 331 380 451 3 7950 7916 1624 3 7924 2897 7...
34397733    1782 9 775 3 857 7916 31 1872 3 1340 7916 6 18...
27787094    2152 3 7961 7916 738 95 9 775 3 311 7916 31 33...
337940      215 3 7960 7916 81 9 439 31 170 1734 362 2193 ...
9782029     215 3 1340 7916 81 6 471 7937 266 367 1462 3 3...
Name: text, Length: 32519, dtype: str

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(
    lowercase=False,                 
    preprocessor=lambda x: x,        
    tokenizer=lambda x: x.split(),   # Tách bằng khoảng trắng
    token_pattern=None               # Tắt regex mặc định
)
X_train = tfidf.fit_transform(X_train)
X_val=tfidf.transform(X_val)
X_test=tfidf.transform(X_test)

In [22]:
X_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1807622 stored elements and shape (32519, 7640)>

In [22]:
# Y_train=np.array(Y_train.to_list())

In [64]:
model = xgb.XGBClassifier(
    tree_method="hist", 
    multi_strategy="multi_output_tree",
    objective="binary:logistic", # Vẫn dùng binary vì mỗi cột là 1 xác suất ĐÚNG/SAI độc lập
    n_estimators=200,            # Số cây
    learning_rate=0.1,
    max_depth=6,
    random_state=42
)

In [66]:
model.fit(
    X_train, Y_train,
    eval_set=[(X_train, Y_train), (X_val, Y_val)], # xem cả train và val
    verbose=True # True = in ra mỗi vòng, verbose=10 = in mỗi 10 vòng
)

[0]	validation_0-logloss:0.54124	validation_1-logloss:0.54170
[1]	validation_0-logloss:0.51123	validation_1-logloss:0.51203
[2]	validation_0-logloss:0.48694	validation_1-logloss:0.48782
[3]	validation_0-logloss:0.46516	validation_1-logloss:0.46601
[4]	validation_0-logloss:0.44669	validation_1-logloss:0.44792
[5]	validation_0-logloss:0.43024	validation_1-logloss:0.43192
[6]	validation_0-logloss:0.41348	validation_1-logloss:0.41555
[7]	validation_0-logloss:0.40018	validation_1-logloss:0.40282
[8]	validation_0-logloss:0.38772	validation_1-logloss:0.39045
[9]	validation_0-logloss:0.37689	validation_1-logloss:0.37966
[10]	validation_0-logloss:0.36541	validation_1-logloss:0.36872
[11]	validation_0-logloss:0.35640	validation_1-logloss:0.36012
[12]	validation_0-logloss:0.34811	validation_1-logloss:0.35243
[13]	validation_0-logloss:0.34021	validation_1-logloss:0.34495
[14]	validation_0-logloss:0.33242	validation_1-logloss:0.33749
[15]	validation_0-logloss:0.32580	validation_1-logloss:0.33108
[16]	validation_0-logloss:0.31892	validation_1-logloss:0.32451
[17]	validation_0-logloss:0.31334	validation_1-logloss:0.31937
[18]	validation_0-logloss:0.30820	validation_1-logloss:0.31454
[19]	validation_0-logloss:0.30347	validation_1-logloss:0.31007
[20]	validation_0-logloss:0.29883	validation_1-logloss:0.30587
[21]	validation_0-logloss:0.29464	validation_1-logloss:0.30192
[22]	validation_0-logloss:0.29056	validation_1-logloss:0.29820
[23]	validation_0-logloss:0.28663	validation_1-logloss:0.29471
[24]	validation_0-logloss:0.28250	validation_1-logloss:0.29099
[25]	validation_0-logloss:0.27923	validation_1-logloss:0.28807
[26]	validation_0-logloss:0.27565	validation_1-logloss:0.28476
[27]	validation_0-logloss:0.27242	validation_1-logloss:0.28164
[28]	validation_0-logloss:0.26940	validation_1-logloss:0.27886
[29]	validation_0-logloss:0.26650	validation_1-logloss:0.27632
[30]	validation_0-logloss:0.26404	validation_1-logloss:0.27407
[31]	validation_0-logloss:0.26131	validation_1-logloss:0.27137
[32]	validation_0-logloss:0.25876	validation_1-logloss:0.26904
[33]	validation_0-logloss:0.25631	validation_1-logloss:0.26704
[34]	validation_0-logloss:0.25327	validation_1-logloss:0.26462
[35]	validation_0-logloss:0.25075	validation_1-logloss:0.26244
[36]	validation_0-logloss:0.24862	validation_1-logloss:0.26065
[37]	validation_0-logloss:0.24694	validation_1-logloss:0.25906
[38]	validation_0-logloss:0.24485	validation_1-logloss:0.25728
[39]	validation_0-logloss:0.24249	validation_1-logloss:0.25554
[40]	validation_0-logloss:0.24087	validation_1-logloss:0.25419
[41]	validation_0-logloss:0.23933	validation_1-logloss:0.25276
[42]	validation_0-logloss:0.23762	validation_1-logloss:0.25129
[43]	validation_0-logloss:0.23566	validation_1-logloss:0.24987
[44]	validation_0-logloss:0.23407	validation_1-logloss:0.24837
[45]	validation_0-logloss:0.23252	validation_1-logloss:0.24711
[46]	validation_0-logloss:0.23075	validation_1-logloss:0.24559
[47]	validation_0-logloss:0.22945	validation_1-logloss:0.24453
[48]	validation_0-logloss:0.22805	validation_1-logloss:0.24336
[49]	validation_0-logloss:0.22689	validation_1-logloss:0.24243
[50]	validation_0-logloss:0.22536	validation_1-logloss:0.24140
[51]	validation_0-logloss:0.22410	validation_1-logloss:0.24033
[52]	validation_0-logloss:0.22280	validation_1-logloss:0.23932
[53]	validation_0-logloss:0.22132	validation_1-logloss:0.23801
[54]	validation_0-logloss:0.22009	validation_1-logloss:0.23708
[55]	validation_0-logloss:0.21891	validation_1-logloss:0.23598
[56]	validation_0-logloss:0.21793	validation_1-logloss:0.23522
[57]	validation_0-logloss:0.21688	validation_1-logloss:0.23436
[58]	validation_0-logloss:0.21583	validation_1-logloss:0.23358
[59]	validation_0-logloss:0.21485	validation_1-logloss:0.23271
[60]	validation_0-logloss:0.21390	validation_1-logloss:0.23198
[61]	validation_0-logloss:0.21289	validation_1-logloss:0.23117
[62]	validation_0-logloss:0.21183	validation_1-logloss:0.23036
[63]	validation_0-logloss:0.21057	validation_1-logloss:0.22946
[64]	validation_0-logloss:0.20973	validation_1-logloss:0.22874
[65]	validation_0-logloss:0.20881	validation_1-logloss:0.22801
[66]	validation_0-logloss:0.20801	validation_1-logloss:0.22730
[67]	validation_0-logloss:0.20708	validation_1-logloss:0.22676
[68]	validation_0-logloss:0.20622	validation_1-logloss:0.22608
[69]	validation_0-logloss:0.20527	validation_1-logloss:0.22550
[70]	validation_0-logloss:0.20431	validation_1-logloss:0.22497
[71]	validation_0-logloss:0.20356	validation_1-logloss:0.22435
[72]	validation_0-logloss:0.20273	validation_1-logloss:0.22378
[73]	validation_0-logloss:0.20206	validation_1-logloss:0.22328
[74]	validation_0-logloss:0.20121	validation_1-logloss:0.22262
[75]	validation_0-logloss:0.20044	validation_1-logloss:0.22195
[76]	validation_0-logloss:0.19970	validation_1-logloss:0.22134
[77]	validation_0-logloss:0.19878	validation_1-logloss:0.22072
[78]	validation_0-logloss:0.19795	validation_1-logloss:0.22017
[79]	validation_0-logloss:0.19729	validation_1-logloss:0.21973
[80]	validation_0-logloss:0.19667	validation_1-logloss:0.21938
[81]	validation_0-logloss:0.19571	validation_1-logloss:0.21887
[82]	validation_0-logloss:0.19494	validation_1-logloss:0.21832
[83]	validation_0-logloss:0.19425	validation_1-logloss:0.21782
[84]	validation_0-logloss:0.19366	validation_1-logloss:0.21734
[85]	validation_0-logloss:0.19302	validation_1-logloss:0.21693
[86]	validation_0-logloss:0.19238	validation_1-logloss:0.21647
[87]	validation_0-logloss:0.19170	validation_1-logloss:0.21597
[88]	validation_0-logloss:0.19110	validation_1-logloss:0.21555
[89]	validation_0-logloss:0.19053	validation_1-logloss:0.21527
[90]	validation_0-logloss:0.18986	validation_1-logloss:0.21487
[91]	validation_0-logloss:0.18930	validation_1-logloss:0.21436
[92]	validation_0-logloss:0.18878	validation_1-logloss:0.21399
[93]	validation_0-logloss:0.18832	validation_1-logloss:0.21366
[94]	validation_0-logloss:0.18783	validation_1-logloss:0.21326
[95]	validation_0-logloss:0.18733	validation_1-logloss:0.21291
[96]	validation_0-logloss:0.18676	validation_1-logloss:0.21254
[97]	validation_0-logloss:0.18622	validation_1-logloss:0.21216
[98]	validation_0-logloss:0.18562	validation_1-logloss:0.21177
[99]	validation_0-logloss:0.18511	validation_1-logloss:0.21141
[100]	validation_0-logloss:0.18469	validation_1-logloss:0.21101
[101]	validation_0-logloss:0.18415	validation_1-logloss:0.21068
[102]	validation_0-logloss:0.18362	validation_1-logloss:0.21039
[103]	validation_0-logloss:0.18304	validation_1-logloss:0.21001
[104]	validation_0-logloss:0.18250	validation_1-logloss:0.20970
[105]	validation_0-logloss:0.18204	validation_1-logloss:0.20926
[106]	validation_0-logloss:0.18158	validation_1-logloss:0.20884
[107]	validation_0-logloss:0.18111	validation_1-logloss:0.20857
[108]	validation_0-logloss:0.18055	validation_1-logloss:0.20829
[109]	validation_0-logloss:0.18021	validation_1-logloss:0.20803
[110]	validation_0-logloss:0.17980	validation_1-logloss:0.20779
[111]	validation_0-logloss:0.17940	validation_1-logloss:0.20759
[112]	validation_0-logloss:0.17893	validation_1-logloss:0.20729
[113]	validation_0-logloss:0.17842	validation_1-logloss:0.20704
[114]	validation_0-logloss:0.17794	validation_1-logloss:0.20668
[115]	validation_0-logloss:0.17757	validation_1-logloss:0.20636
[116]	validation_0-logloss:0.17702	validation_1-logloss:0.20611
[117]	validation_0-logloss:0.17643	validation_1-logloss:0.20573
[118]	validation_0-logloss:0.17604	validation_1-logloss:0.20552
[119]	validation_0-logloss:0.17544	validation_1-logloss:0.20521
[120]	validation_0-logloss:0.17510	validation_1-logloss:0.20496
[121]	validation_0-logloss:0.17472	validation_1-logloss:0.20463
[122]	validation_0-logloss:0.17413	validation_1-logloss:0.20423
[123]	validation_0-logloss:0.17378	validation_1-logloss:0.20403
[124]	validation_0-logloss:0.17334	validation_1-logloss:0.20379
[125]	validation_0-logloss:0.17296	validation_1-logloss:0.20343
[126]	validation_0-logloss:0.17264	validation_1-logloss:0.20334
[127]	validation_0-logloss:0.17227	validation_1-logloss:0.20314
[128]	validation_0-logloss:0.17183	validation_1-logloss:0.20287
[129]	validation_0-logloss:0.17139	validation_1-logloss:0.20253
[130]	validation_0-logloss:0.17092	validation_1-logloss:0.20219
[131]	validation_0-logloss:0.17047	validation_1-logloss:0.20196
[132]	validation_0-logloss:0.17007	validation_1-logloss:0.20178
[133]	validation_0-logloss:0.16965	validation_1-logloss:0.20154
[134]	validation_0-logloss:0.16930	validation_1-logloss:0.20130
[135]	validation_0-logloss:0.16888	validation_1-logloss:0.20112
[136]	validation_0-logloss:0.16858	validation_1-logloss:0.20087
[137]	validation_0-logloss:0.16831	validation_1-logloss:0.20071
[138]	validation_0-logloss:0.16790	validation_1-logloss:0.20041
[139]	validation_0-logloss:0.16748	validation_1-logloss:0.20026
[140]	validation_0-logloss:0.16721	validation_1-logloss:0.20006
[141]	validation_0-logloss:0.16689	validation_1-logloss:0.19986
[142]	validation_0-logloss:0.16639	validation_1-logloss:0.19963
[143]	validation_0-logloss:0.16583	validation_1-logloss:0.19946
[144]	validation_0-logloss:0.16524	validation_1-logloss:0.19911
[145]	validation_0-logloss:0.16481	validation_1-logloss:0.19895
[146]	validation_0-logloss:0.16456	validation_1-logloss:0.19874
[147]	validation_0-logloss:0.16418	validation_1-logloss:0.19857
[148]	validation_0-logloss:0.16381	validation_1-logloss:0.19833
[149]	validation_0-logloss:0.16347	validation_1-logloss:0.19810
[150]	validation_0-logloss:0.16321	validation_1-logloss:0.19792
[151]	validation_0-logloss:0.16292	validation_1-logloss:0.19780
[152]	validation_0-logloss:0.16256	validation_1-logloss:0.19767
[153]	validation_0-logloss:0.16229	validation_1-logloss:0.19750
[154]	validation_0-logloss:0.16198	validation_1-logloss:0.19731
[155]	validation_0-logloss:0.16151	validation_1-logloss:0.19707
[156]	validation_0-logloss:0.16129	validation_1-logloss:0.19694
[157]	validation_0-logloss:0.16093	validation_1-logloss:0.19679
[158]	validation_0-logloss:0.16057	validation_1-logloss:0.19656
[159]	validation_0-logloss:0.16028	validation_1-logloss:0.19633
[160]	validation_0-logloss:0.16000	validation_1-logloss:0.19605
[161]	validation_0-logloss:0.15963	validation_1-logloss:0.19582
[162]	validation_0-logloss:0.15935	validation_1-logloss:0.19565
[163]	validation_0-logloss:0.15903	validation_1-logloss:0.19554
[164]	validation_0-logloss:0.15874	validation_1-logloss:0.19537
[165]	validation_0-logloss:0.15851	validation_1-logloss:0.19523
[166]	validation_0-logloss:0.15824	validation_1-logloss:0.19504
[167]	validation_0-logloss:0.15795	validation_1-logloss:0.19484
[168]	validation_0-logloss:0.15757	validation_1-logloss:0.19463
[169]	validation_0-logloss:0.15730	validation_1-logloss:0.19457
[170]	validation_0-logloss:0.15701	validation_1-logloss:0.19447
[171]	validation_0-logloss:0.15667	validation_1-logloss:0.19434
[172]	validation_0-logloss:0.15643	validation_1-logloss:0.19427
[173]	validation_0-logloss:0.15621	validation_1-logloss:0.19413
[174]	validation_0-logloss:0.15589	validation_1-logloss:0.19395
[175]	validation_0-logloss:0.15553	validation_1-logloss:0.19377
[176]	validation_0-logloss:0.15531	validation_1-logloss:0.19359
[177]	validation_0-logloss:0.15508	validation_1-logloss:0.19347
[178]	validation_0-logloss:0.15483	validation_1-logloss:0.19331
[179]	validation_0-logloss:0.15463	validation_1-logloss:0.19319
[180]	validation_0-logloss:0.15444	validation_1-logloss:0.19307
[181]	validation_0-logloss:0.15410	validation_1-logloss:0.19292
[182]	validation_0-logloss:0.15388	validation_1-logloss:0.19278
[183]	validation_0-logloss:0.15365	validation_1-logloss:0.19266
[184]	validation_0-logloss:0.15341	validation_1-logloss:0.19262
[185]	validation_0-logloss:0.15316	validation_1-logloss:0.19251
[186]	validation_0-logloss:0.15281	validation_1-logloss:0.19247
[187]	validation_0-logloss:0.15247	validation_1-logloss:0.19243
[188]	validation_0-logloss:0.15222	validation_1-logloss:0.19235
[189]	validation_0-logloss:0.15196	validation_1-logloss:0.19225
[190]	validation_0-logloss:0.15169	validation_1-logloss:0.19214
[191]	validation_0-logloss:0.15147	validation_1-logloss:0.19205
[192]	validation_0-logloss:0.15118	validation_1-logloss:0.19190
[193]	validation_0-logloss:0.15092	validation_1-logloss:0.19177
[194]	validation_0-logloss:0.15064	validation_1-logloss:0.19167
[195]	validation_0-logloss:0.15039	validation_1-logloss:0.19158
[196]	validation_0-logloss:0.15010	validation_1-logloss:0.19146
[197]	validation_0-logloss:0.14983	validation_1-logloss:0.19142
[198]	validation_0-logloss:0.14961	validation_1-logloss:0.19129
[199]	validation_0-logloss:0.14934	validation_1-logloss:0.19122

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy='multi_output_tree',
              n_estimators=200, n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
model2 = xgb.XGBClassifier(
    tree_method="hist", 
    multi_strategy="multi_output_tree",
    objective="binary:logistic", # Vẫn dùng binary vì mỗi cột là 1 xác suất ĐÚNG/SAI độc lập
    n_estimators=200,            # Số cây
    learning_rate=0.1,
    max_depth=6,
    random_state=42,

)
model2.fit(
    X_train, Y_train,
    xgb_model=model.get_booster(),
    eval_set=[(X_train, Y_train), (X_val, Y_val)], # xem cả train và val
    verbose=True # True = in ra mỗi vòng, verbose=10 = in mỗi 10 vòng
)

[0]	validation_0-logloss:0.14903	validation_1-logloss:0.19115
[1]	validation_0-logloss:0.14886	validation_1-logloss:0.19108
[2]	validation_0-logloss:0.14866	validation_1-logloss:0.19103
[3]	validation_0-logloss:0.14842	validation_1-logloss:0.19080
[4]	validation_0-logloss:0.14827	validation_1-logloss:0.19068
[5]	validation_0-logloss:0.14805	validation_1-logloss:0.19063
[6]	validation_0-logloss:0.14781	validation_1-logloss:0.19051
[7]	validation_0-logloss:0.14742	validation_1-logloss:0.19038
[8]	validation_0-logloss:0.14721	validation_1-logloss:0.19034
[9]	validation_0-logloss:0.14696	validation_1-logloss:0.19023
[10]	validation_0-logloss:0.14660	validation_1-logloss:0.19007
[11]	validation_0-logloss:0.14643	validation_1-logloss:0.18999
[12]	validation_0-logloss:0.14620	validation_1-logloss:0.18987
[13]	validation_0-logloss:0.14591	validation_1-logloss:0.18973
[14]	validation_0-logloss:0.14562	validation_1-logloss:0.18960
[15]	validation_0-logloss:0.14542	validation_1-logloss:0.18951
[16]	validation_0-logloss:0.14523	validation_1-logloss:0.18936
[17]	validation_0-logloss:0.14509	validation_1-logloss:0.18929
[18]	validation_0-logloss:0.14485	validation_1-logloss:0.18924
[19]	validation_0-logloss:0.14465	validation_1-logloss:0.18917
[20]	validation_0-logloss:0.14448	validation_1-logloss:0.18911
[21]	validation_0-logloss:0.14426	validation_1-logloss:0.18907
[22]	validation_0-logloss:0.14402	validation_1-logloss:0.18896
[23]	validation_0-logloss:0.14384	validation_1-logloss:0.18887
[24]	validation_0-logloss:0.14367	validation_1-logloss:0.18875
[25]	validation_0-logloss:0.14346	validation_1-logloss:0.18866
[26]	validation_0-logloss:0.14322	validation_1-logloss:0.18865
[27]	validation_0-logloss:0.14306	validation_1-logloss:0.18851
[28]	validation_0-logloss:0.14287	validation_1-logloss:0.18837
[29]	validation_0-logloss:0.14262	validation_1-logloss:0.18827
[30]	validation_0-logloss:0.14242	validation_1-logloss:0.18821
[31]	validation_0-logloss:0.14224	validation_1-logloss:0.18818
[32]	validation_0-logloss:0.14196	validation_1-logloss:0.18813
[33]	validation_0-logloss:0.14170	validation_1-logloss:0.18808
[34]	validation_0-logloss:0.14154	validation_1-logloss:0.18801
[35]	validation_0-logloss:0.14134	validation_1-logloss:0.18796
[36]	validation_0-logloss:0.14116	validation_1-logloss:0.18786
[37]	validation_0-logloss:0.14097	validation_1-logloss:0.18776
[38]	validation_0-logloss:0.14085	validation_1-logloss:0.18770
[39]	validation_0-logloss:0.14057	validation_1-logloss:0.18766
[40]	validation_0-logloss:0.14041	validation_1-logloss:0.18758
[41]	validation_0-logloss:0.14023	validation_1-logloss:0.18753
[42]	validation_0-logloss:0.14005	validation_1-logloss:0.18748
[43]	validation_0-logloss:0.13990	validation_1-logloss:0.18739
[44]	validation_0-logloss:0.13968	validation_1-logloss:0.18727
[45]	validation_0-logloss:0.13951	validation_1-logloss:0.18723
[46]	validation_0-logloss:0.13935	validation_1-logloss:0.18716
[47]	validation_0-logloss:0.13915	validation_1-logloss:0.18709
[48]	validation_0-logloss:0.13892	validation_1-logloss:0.18702
[49]	validation_0-logloss:0.13862	validation_1-logloss:0.18691
[50]	validation_0-logloss:0.13840	validation_1-logloss:0.18679
[51]	validation_0-logloss:0.13825	validation_1-logloss:0.18675
[52]	validation_0-logloss:0.13807	validation_1-logloss:0.18672
[53]	validation_0-logloss:0.13787	validation_1-logloss:0.18666
[54]	validation_0-logloss:0.13765	validation_1-logloss:0.18663
[55]	validation_0-logloss:0.13751	validation_1-logloss:0.18650
[56]	validation_0-logloss:0.13729	validation_1-logloss:0.18643
[57]	validation_0-logloss:0.13709	validation_1-logloss:0.18636
[58]	validation_0-logloss:0.13687	validation_1-logloss:0.18629
[59]	validation_0-logloss:0.13658	validation_1-logloss:0.18623
[60]	validation_0-logloss:0.13642	validation_1-logloss:0.18620
[61]	validation_0-logloss:0.13626	validation_1-logloss:0.18618
[62]	validation_0-logloss:0.13616	validation_1-logloss:0.18610
[63]	validation_0-logloss:0.13600	validation_1-logloss:0.18599
[64]	validation_0-logloss:0.13579	validation_1-logloss:0.18594
[65]	validation_0-logloss:0.13561	validation_1-logloss:0.18592
[66]	validation_0-logloss:0.13548	validation_1-logloss:0.18584
[67]	validation_0-logloss:0.13534	validation_1-logloss:0.18577
[68]	validation_0-logloss:0.13521	validation_1-logloss:0.18574
[69]	validation_0-logloss:0.13507	validation_1-logloss:0.18566
[70]	validation_0-logloss:0.13479	validation_1-logloss:0.18552
[71]	validation_0-logloss:0.13464	validation_1-logloss:0.18545
[72]	validation_0-logloss:0.13447	validation_1-logloss:0.18542
[73]	validation_0-logloss:0.13436	validation_1-logloss:0.18537
[74]	validation_0-logloss:0.13404	validation_1-logloss:0.18538
[75]	validation_0-logloss:0.13379	validation_1-logloss:0.18532
[76]	validation_0-logloss:0.13353	validation_1-logloss:0.18527
[77]	validation_0-logloss:0.13317	validation_1-logloss:0.18526
[78]	validation_0-logloss:0.13305	validation_1-logloss:0.18519
[79]	validation_0-logloss:0.13291	validation_1-logloss:0.18511
[80]	validation_0-logloss:0.13278	validation_1-logloss:0.18500
[81]	validation_0-logloss:0.13261	validation_1-logloss:0.18497
[82]	validation_0-logloss:0.13235	validation_1-logloss:0.18498
[83]	validation_0-logloss:0.13219	validation_1-logloss:0.18503
[84]	validation_0-logloss:0.13197	validation_1-logloss:0.18503
[85]	validation_0-logloss:0.13180	validation_1-logloss:0.18489
[86]	validation_0-logloss:0.13161	validation_1-logloss:0.18485
[87]	validation_0-logloss:0.13144	validation_1-logloss:0.18482
[88]	validation_0-logloss:0.13131	validation_1-logloss:0.18478
[89]	validation_0-logloss:0.13116	validation_1-logloss:0.18477
[90]	validation_0-logloss:0.13100	validation_1-logloss:0.18472
[91]	validation_0-logloss:0.13085	validation_1-logloss:0.18468
[92]	validation_0-logloss:0.13074	validation_1-logloss:0.18463
[93]	validation_0-logloss:0.13049	validation_1-logloss:0.18459
[94]	validation_0-logloss:0.13035	validation_1-logloss:0.18453
[95]	validation_0-logloss:0.13021	validation_1-logloss:0.18447
[96]	validation_0-logloss:0.13009	validation_1-logloss:0.18442
[97]	validation_0-logloss:0.12993	validation_1-logloss:0.18436
[98]	validation_0-logloss:0.12973	validation_1-logloss:0.18433
[99]	validation_0-logloss:0.12964	validation_1-logloss:0.18431
[100]	validation_0-logloss:0.12952	validation_1-logloss:0.18429
[101]	validation_0-logloss:0.12932	validation_1-logloss:0.18423
[102]	validation_0-logloss:0.12921	validation_1-logloss:0.18421
[103]	validation_0-logloss:0.12902	validation_1-logloss:0.18413
[104]	validation_0-logloss:0.12876	validation_1-logloss:0.18405
[105]	validation_0-logloss:0.12860	validation_1-logloss:0.18403
[106]	validation_0-logloss:0.12837	validation_1-logloss:0.18398
[107]	validation_0-logloss:0.12822	validation_1-logloss:0.18392
[108]	validation_0-logloss:0.12808	validation_1-logloss:0.18386
[109]	validation_0-logloss:0.12796	validation_1-logloss:0.18380
[110]	validation_0-logloss:0.12780	validation_1-logloss:0.18369
[111]	validation_0-logloss:0.12759	validation_1-logloss:0.18366
[112]	validation_0-logloss:0.12745	validation_1-logloss:0.18363
[113]	validation_0-logloss:0.12706	validation_1-logloss:0.18352
[114]	validation_0-logloss:0.12691	validation_1-logloss:0.18346
[115]	validation_0-logloss:0.12677	validation_1-logloss:0.18336
[116]	validation_0-logloss:0.12659	validation_1-logloss:0.18333
[117]	validation_0-logloss:0.12645	validation_1-logloss:0.18330
[118]	validation_0-logloss:0.12632	validation_1-logloss:0.18324
[119]	validation_0-logloss:0.12612	validation_1-logloss:0.18324
[120]	validation_0-logloss:0.12602	validation_1-logloss:0.18321
[121]	validation_0-logloss:0.12582	validation_1-logloss:0.18318
[122]	validation_0-logloss:0.12566	validation_1-logloss:0.18310
[123]	validation_0-logloss:0.12551	validation_1-logloss:0.18302
[124]	validation_0-logloss:0.12533	validation_1-logloss:0.18295
[125]	validation_0-logloss:0.12520	validation_1-logloss:0.18292
[126]	validation_0-logloss:0.12505	validation_1-logloss:0.18289
[127]	validation_0-logloss:0.12488	validation_1-logloss:0.18283
[128]	validation_0-logloss:0.12470	validation_1-logloss:0.18279
[129]	validation_0-logloss:0.12456	validation_1-logloss:0.18274
[130]	validation_0-logloss:0.12436	validation_1-logloss:0.18276
[131]	validation_0-logloss:0.12423	validation_1-logloss:0.18274
[132]	validation_0-logloss:0.12414	validation_1-logloss:0.18274
[133]	validation_0-logloss:0.12399	validation_1-logloss:0.18269
[134]	validation_0-logloss:0.12380	validation_1-logloss:0.18260
[135]	validation_0-logloss:0.12366	validation_1-logloss:0.18260
[136]	validation_0-logloss:0.12352	validation_1-logloss:0.18254
[137]	validation_0-logloss:0.12334	validation_1-logloss:0.18252
[138]	validation_0-logloss:0.12324	validation_1-logloss:0.18248
[139]	validation_0-logloss:0.12303	validation_1-logloss:0.18244
[140]	validation_0-logloss:0.12291	validation_1-logloss:0.18241
[141]	validation_0-logloss:0.12281	validation_1-logloss:0.18234
[142]	validation_0-logloss:0.12269	validation_1-logloss:0.18230
[143]	validation_0-logloss:0.12257	validation_1-logloss:0.18230
[144]	validation_0-logloss:0.12242	validation_1-logloss:0.18233
[145]	validation_0-logloss:0.12226	validation_1-logloss:0.18231
[146]	validation_0-logloss:0.12207	validation_1-logloss:0.18224
[147]	validation_0-logloss:0.12185	validation_1-logloss:0.18217
[148]	validation_0-logloss:0.12160	validation_1-logloss:0.18216
[149]	validation_0-logloss:0.12150	validation_1-logloss:0.18208
[150]	validation_0-logloss:0.12137	validation_1-logloss:0.18202
[151]	validation_0-logloss:0.12126	validation_1-logloss:0.18197
[152]	validation_0-logloss:0.12113	validation_1-logloss:0.18194
[153]	validation_0-logloss:0.12100	validation_1-logloss:0.18188
[154]	validation_0-logloss:0.12091	validation_1-logloss:0.18187
[155]	validation_0-logloss:0.12079	validation_1-logloss:0.18185
[156]	validation_0-logloss:0.12072	validation_1-logloss:0.18183
[157]	validation_0-logloss:0.12061	validation_1-logloss:0.18180
[158]	validation_0-logloss:0.12048	validation_1-logloss:0.18172
[159]	validation_0-logloss:0.12036	validation_1-logloss:0.18164
[160]	validation_0-logloss:0.12020	validation_1-logloss:0.18163
[161]	validation_0-logloss:0.11996	validation_1-logloss:0.18161
[162]	validation_0-logloss:0.11981	validation_1-logloss:0.18159
[163]	validation_0-logloss:0.11970	validation_1-logloss:0.18156
[164]	validation_0-logloss:0.11954	validation_1-logloss:0.18159
[165]	validation_0-logloss:0.11942	validation_1-logloss:0.18152
[166]	validation_0-logloss:0.11932	validation_1-logloss:0.18146
[167]	validation_0-logloss:0.11922	validation_1-logloss:0.18142
[168]	validation_0-logloss:0.11911	validation_1-logloss:0.18138
[169]	validation_0-logloss:0.11897	validation_1-logloss:0.18134
[170]	validation_0-logloss:0.11882	validation_1-logloss:0.18130
[171]	validation_0-logloss:0.11872	validation_1-logloss:0.18128
[172]	validation_0-logloss:0.11858	validation_1-logloss:0.18129
[173]	validation_0-logloss:0.11846	validation_1-logloss:0.18129
[174]	validation_0-logloss:0.11835	validation_1-logloss:0.18124
[175]	validation_0-logloss:0.11825	validation_1-logloss:0.18125
[176]	validation_0-logloss:0.11809	validation_1-logloss:0.18120
[177]	validation_0-logloss:0.11794	validation_1-logloss:0.18119
[178]	validation_0-logloss:0.11777	validation_1-logloss:0.18115
[179]	validation_0-logloss:0.11766	validation_1-logloss:0.18112
[180]	validation_0-logloss:0.11746	validation_1-logloss:0.18112
[181]	validation_0-logloss:0.11736	validation_1-logloss:0.18111
[182]	validation_0-logloss:0.11727	validation_1-logloss:0.18107
[183]	validation_0-logloss:0.11719	validation_1-logloss:0.18101
[184]	validation_0-logloss:0.11707	validation_1-logloss:0.18098
[185]	validation_0-logloss:0.11691	validation_1-logloss:0.18096
[186]	validation_0-logloss:0.11675	validation_1-logloss:0.18093
[187]	validation_0-logloss:0.11662	validation_1-logloss:0.18091
[188]	validation_0-logloss:0.11651	validation_1-logloss:0.18092
[189]	validation_0-logloss:0.11642	validation_1-logloss:0.18093
[190]	validation_0-logloss:0.11630	validation_1-logloss:0.18095
[191]	validation_0-logloss:0.11621	validation_1-logloss:0.18091
[192]	validation_0-logloss:0.11607	validation_1-logloss:0.18089
[193]	validation_0-logloss:0.11592	validation_1-logloss:0.18086
[194]	validation_0-logloss:0.11583	validation_1-logloss:0.18084
[195]	validation_0-logloss:0.11572	validation_1-logloss:0.18085
[196]	validation_0-logloss:0.11552	validation_1-logloss:0.18081
[197]	validation_0-logloss:0.11542	validation_1-logloss:0.18077
[198]	validation_0-logloss:0.11534	validation_1-logloss:0.18072
[199]	validation_0-logloss:0.11525	validation_1-logloss:0.18070

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy='multi_output_tree',
              n_estimators=200, n_jobs=None, num_parallel_tree=None, ...)

In [76]:
model3 = xgb.XGBClassifier(
    tree_method="hist", 
    multi_strategy="multi_output_tree",
    objective="binary:logistic", # Vẫn dùng binary vì mỗi cột là 1 xác suất ĐÚNG/SAI độc lập
    n_estimators=100,            # Số cây
    learning_rate=0.1,
    max_depth=6,
    random_state=42,

)
model3.fit(
    X_train, Y_train,
    xgb_model=model2.get_booster(),
    eval_set=[(X_train, Y_train), (X_val, Y_val)], # xem cả train và val
    verbose=True # True = in ra mỗi vòng, verbose=10 = in mỗi 10 vòng
)

[0]	validation_0-logloss:0.11515	validation_1-logloss:0.18072
[1]	validation_0-logloss:0.11504	validation_1-logloss:0.18064
[2]	validation_0-logloss:0.11494	validation_1-logloss:0.18064
[3]	validation_0-logloss:0.11480	validation_1-logloss:0.18062
[4]	validation_0-logloss:0.11473	validation_1-logloss:0.18061
[5]	validation_0-logloss:0.11464	validation_1-logloss:0.18058
[6]	validation_0-logloss:0.11456	validation_1-logloss:0.18052
[7]	validation_0-logloss:0.11438	validation_1-logloss:0.18047
[8]	validation_0-logloss:0.11431	validation_1-logloss:0.18047
[9]	validation_0-logloss:0.11420	validation_1-logloss:0.18043
[10]	validation_0-logloss:0.11408	validation_1-logloss:0.18037
[11]	validation_0-logloss:0.11399	validation_1-logloss:0.18035
[12]	validation_0-logloss:0.11388	validation_1-logloss:0.18033
[13]	validation_0-logloss:0.11381	validation_1-logloss:0.18027
[14]	validation_0-logloss:0.11366	validation_1-logloss:0.18025
[15]	validation_0-logloss:0.11341	validation_1-logloss:0.18020
[16]	validation_0-logloss:0.11332	validation_1-logloss:0.18013
[17]	validation_0-logloss:0.11322	validation_1-logloss:0.18012
[18]	validation_0-logloss:0.11312	validation_1-logloss:0.18010
[19]	validation_0-logloss:0.11303	validation_1-logloss:0.18010
[20]	validation_0-logloss:0.11294	validation_1-logloss:0.18007
[21]	validation_0-logloss:0.11286	validation_1-logloss:0.18001
[22]	validation_0-logloss:0.11279	validation_1-logloss:0.17999
[23]	validation_0-logloss:0.11269	validation_1-logloss:0.17997
[24]	validation_0-logloss:0.11255	validation_1-logloss:0.17993
[25]	validation_0-logloss:0.11243	validation_1-logloss:0.17992
[26]	validation_0-logloss:0.11237	validation_1-logloss:0.17989
[27]	validation_0-logloss:0.11223	validation_1-logloss:0.17987
[28]	validation_0-logloss:0.11208	validation_1-logloss:0.17983
[29]	validation_0-logloss:0.11196	validation_1-logloss:0.17979
[30]	validation_0-logloss:0.11187	validation_1-logloss:0.17976
[31]	validation_0-logloss:0.11173	validation_1-logloss:0.17976
[32]	validation_0-logloss:0.11161	validation_1-logloss:0.17975
[33]	validation_0-logloss:0.11151	validation_1-logloss:0.17974
[34]	validation_0-logloss:0.11143	validation_1-logloss:0.17970
[35]	validation_0-logloss:0.11128	validation_1-logloss:0.17968
[36]	validation_0-logloss:0.11120	validation_1-logloss:0.17966
[37]	validation_0-logloss:0.11108	validation_1-logloss:0.17963
[38]	validation_0-logloss:0.11097	validation_1-logloss:0.17962
[39]	validation_0-logloss:0.11088	validation_1-logloss:0.17961
[40]	validation_0-logloss:0.11074	validation_1-logloss:0.17960
[41]	validation_0-logloss:0.11068	validation_1-logloss:0.17957
[42]	validation_0-logloss:0.11059	validation_1-logloss:0.17955
[43]	validation_0-logloss:0.11048	validation_1-logloss:0.17950
[44]	validation_0-logloss:0.11035	validation_1-logloss:0.17948
[45]	validation_0-logloss:0.11019	validation_1-logloss:0.17947
[46]	validation_0-logloss:0.11008	validation_1-logloss:0.17945
[47]	validation_0-logloss:0.10998	validation_1-logloss:0.17942
[48]	validation_0-logloss:0.10986	validation_1-logloss:0.17941
[49]	validation_0-logloss:0.10972	validation_1-logloss:0.17943
[50]	validation_0-logloss:0.10961	validation_1-logloss:0.17941
[51]	validation_0-logloss:0.10954	validation_1-logloss:0.17939
[52]	validation_0-logloss:0.10940	validation_1-logloss:0.17933
[53]	validation_0-logloss:0.10933	validation_1-logloss:0.17932
[54]	validation_0-logloss:0.10925	validation_1-logloss:0.17929
[55]	validation_0-logloss:0.10914	validation_1-logloss:0.17928
[56]	validation_0-logloss:0.10900	validation_1-logloss:0.17929
[57]	validation_0-logloss:0.10888	validation_1-logloss:0.17923
[58]	validation_0-logloss:0.10877	validation_1-logloss:0.17921
[59]	validation_0-logloss:0.10870	validation_1-logloss:0.17921
[60]	validation_0-logloss:0.10853	validation_1-logloss:0.17922
[61]	validation_0-logloss:0.10837	validation_1-logloss:0.17922
[62]	validation_0-logloss:0.10830	validation_1-logloss:0.17920
[63]	validation_0-logloss:0.10818	validation_1-logloss:0.17920
[64]	validation_0-logloss:0.10808	validation_1-logloss:0.17919
[65]	validation_0-logloss:0.10802	validation_1-logloss:0.17917
[66]	validation_0-logloss:0.10788	validation_1-logloss:0.17917
[67]	validation_0-logloss:0.10779	validation_1-logloss:0.17915
[68]	validation_0-logloss:0.10770	validation_1-logloss:0.17916
[69]	validation_0-logloss:0.10758	validation_1-logloss:0.17914
[70]	validation_0-logloss:0.10749	validation_1-logloss:0.17910
[71]	validation_0-logloss:0.10743	validation_1-logloss:0.17911
[72]	validation_0-logloss:0.10733	validation_1-logloss:0.17911
[73]	validation_0-logloss:0.10721	validation_1-logloss:0.17914
[74]	validation_0-logloss:0.10716	validation_1-logloss:0.17914
[75]	validation_0-logloss:0.10702	validation_1-logloss:0.17915
[76]	validation_0-logloss:0.10694	validation_1-logloss:0.17913
[77]	validation_0-logloss:0.10684	validation_1-logloss:0.17910
[78]	validation_0-logloss:0.10677	validation_1-logloss:0.17904
[79]	validation_0-logloss:0.10667	validation_1-logloss:0.17904
[80]	validation_0-logloss:0.10655	validation_1-logloss:0.17901
[81]	validation_0-logloss:0.10643	validation_1-logloss:0.17902
[82]	validation_0-logloss:0.10637	validation_1-logloss:0.17901
[83]	validation_0-logloss:0.10628	validation_1-logloss:0.17902
[84]	validation_0-logloss:0.10616	validation_1-logloss:0.17900
[85]	validation_0-logloss:0.10608	validation_1-logloss:0.17901
[86]	validation_0-logloss:0.10599	validation_1-logloss:0.17899
[87]	validation_0-logloss:0.10592	validation_1-logloss:0.17897
[88]	validation_0-logloss:0.10579	validation_1-logloss:0.17900
[89]	validation_0-logloss:0.10571	validation_1-logloss:0.17897
[90]	validation_0-logloss:0.10561	validation_1-logloss:0.17894
[91]	validation_0-logloss:0.10555	validation_1-logloss:0.17889
[92]	validation_0-logloss:0.10544	validation_1-logloss:0.17888
[93]	validation_0-logloss:0.10531	validation_1-logloss:0.17891
[94]	validation_0-logloss:0.10523	validation_1-logloss:0.17889
[95]	validation_0-logloss:0.10516	validation_1-logloss:0.17888
[96]	validation_0-logloss:0.10499	validation_1-logloss:0.17888
[97]	validation_0-logloss:0.10491	validation_1-logloss:0.17887
[98]	validation_0-logloss:0.10483	validation_1-logloss:0.17888
[99]	validation_0-logloss:0.10472	validation_1-logloss:0.17884

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy='multi_output_tree',
              n_estimators=100, n_jobs=None, num_parallel_tree=None, ...)

In [79]:
model4 = xgb.XGBClassifier(
    tree_method="hist", 
    multi_strategy="multi_output_tree",
    objective="binary:logistic", # Vẫn dùng binary vì mỗi cột là 1 xác suất ĐÚNG/SAI độc lập
    n_estimators=200,            # Số cây
    learning_rate=0.1,
    max_depth=6,
    random_state=42,

)
model4.fit(
    X_train, Y_train,
    xgb_model=model3.get_booster(),
    eval_set=[(X_train, Y_train), (X_val, Y_val)], # xem cả train và val
    verbose=True # True = in ra mỗi vòng, verbose=10 = in mỗi 10 vòng
)

[0]	validation_0-logloss:0.10463	validation_1-logloss:0.17886
[1]	validation_0-logloss:0.10448	validation_1-logloss:0.17885
[2]	validation_0-logloss:0.10442	validation_1-logloss:0.17884
[3]	validation_0-logloss:0.10428	validation_1-logloss:0.17881
[4]	validation_0-logloss:0.10415	validation_1-logloss:0.17881
[5]	validation_0-logloss:0.10402	validation_1-logloss:0.17882
[6]	validation_0-logloss:0.10385	validation_1-logloss:0.17880
[7]	validation_0-logloss:0.10379	validation_1-logloss:0.17880
[8]	validation_0-logloss:0.10371	validation_1-logloss:0.17877
[9]	validation_0-logloss:0.10362	validation_1-logloss:0.17873
[10]	validation_0-logloss:0.10351	validation_1-logloss:0.17873
[11]	validation_0-logloss:0.10340	validation_1-logloss:0.17870
[12]	validation_0-logloss:0.10329	validation_1-logloss:0.17868
[13]	validation_0-logloss:0.10321	validation_1-logloss:0.17868
[14]	validation_0-logloss:0.10315	validation_1-logloss:0.17864
[15]	validation_0-logloss:0.10308	validation_1-logloss:0.17864
[16]	validation_0-logloss:0.10298	validation_1-logloss:0.17859
[17]	validation_0-logloss:0.10289	validation_1-logloss:0.17855
[18]	validation_0-logloss:0.10279	validation_1-logloss:0.17850
[19]	validation_0-logloss:0.10266	validation_1-logloss:0.17849
[20]	validation_0-logloss:0.10256	validation_1-logloss:0.17850
[21]	validation_0-logloss:0.10249	validation_1-logloss:0.17850
[22]	validation_0-logloss:0.10242	validation_1-logloss:0.17846
[23]	validation_0-logloss:0.10231	validation_1-logloss:0.17848
[24]	validation_0-logloss:0.10221	validation_1-logloss:0.17847
[25]	validation_0-logloss:0.10215	validation_1-logloss:0.17845
[26]	validation_0-logloss:0.10208	validation_1-logloss:0.17844
[27]	validation_0-logloss:0.10192	validation_1-logloss:0.17846
[28]	validation_0-logloss:0.10182	validation_1-logloss:0.17845
[29]	validation_0-logloss:0.10175	validation_1-logloss:0.17840
[30]	validation_0-logloss:0.10168	validation_1-logloss:0.17839
[31]	validation_0-logloss:0.10158	validation_1-logloss:0.17836
[32]	validation_0-logloss:0.10148	validation_1-logloss:0.17832
[33]	validation_0-logloss:0.10136	validation_1-logloss:0.17833
[34]	validation_0-logloss:0.10126	validation_1-logloss:0.17831
[35]	validation_0-logloss:0.10116	validation_1-logloss:0.17833
[36]	validation_0-logloss:0.10107	validation_1-logloss:0.17831
[37]	validation_0-logloss:0.10093	validation_1-logloss:0.17830
[38]	validation_0-logloss:0.10085	validation_1-logloss:0.17829
[39]	validation_0-logloss:0.10078	validation_1-logloss:0.17828
[40]	validation_0-logloss:0.10073	validation_1-logloss:0.17824
[41]	validation_0-logloss:0.10063	validation_1-logloss:0.17824
[42]	validation_0-logloss:0.10053	validation_1-logloss:0.17822
[43]	validation_0-logloss:0.10038	validation_1-logloss:0.17820
[44]	validation_0-logloss:0.10029	validation_1-logloss:0.17816
[45]	validation_0-logloss:0.10021	validation_1-logloss:0.17815
[46]	validation_0-logloss:0.10012	validation_1-logloss:0.17817
[47]	validation_0-logloss:0.10005	validation_1-logloss:0.17815
[48]	validation_0-logloss:0.09997	validation_1-logloss:0.17815
[49]	validation_0-logloss:0.09987	validation_1-logloss:0.17815
[50]	validation_0-logloss:0.09981	validation_1-logloss:0.17815
[51]	validation_0-logloss:0.09975	validation_1-logloss:0.17814
[52]	validation_0-logloss:0.09969	validation_1-logloss:0.17811
[53]	validation_0-logloss:0.09961	validation_1-logloss:0.17811
[54]	validation_0-logloss:0.09953	validation_1-logloss:0.17811
[55]	validation_0-logloss:0.09945	validation_1-logloss:0.17810
[56]	validation_0-logloss:0.09937	validation_1-logloss:0.17807
[57]	validation_0-logloss:0.09928	validation_1-logloss:0.17802
[58]	validation_0-logloss:0.09916	validation_1-logloss:0.17799
[59]	validation_0-logloss:0.09904	validation_1-logloss:0.17800
[60]	validation_0-logloss:0.09891	validation_1-logloss:0.17798
[61]	validation_0-logloss:0.09883	validation_1-logloss:0.17798
[62]	validation_0-logloss:0.09877	validation_1-logloss:0.17798
[63]	validation_0-logloss:0.09870	validation_1-logloss:0.17796
[64]	validation_0-logloss:0.09863	validation_1-logloss:0.17799
[65]	validation_0-logloss:0.09855	validation_1-logloss:0.17795
[66]	validation_0-logloss:0.09847	validation_1-logloss:0.17793
[67]	validation_0-logloss:0.09838	validation_1-logloss:0.17791
[68]	validation_0-logloss:0.09831	validation_1-logloss:0.17788
[69]	validation_0-logloss:0.09824	validation_1-logloss:0.17788
[70]	validation_0-logloss:0.09809	validation_1-logloss:0.17786
[71]	validation_0-logloss:0.09804	validation_1-logloss:0.17784
[72]	validation_0-logloss:0.09796	validation_1-logloss:0.17778
[73]	validation_0-logloss:0.09791	validation_1-logloss:0.17778
[74]	validation_0-logloss:0.09777	validation_1-logloss:0.17778
[75]	validation_0-logloss:0.09772	validation_1-logloss:0.17777
[76]	validation_0-logloss:0.09765	validation_1-logloss:0.17774
[77]	validation_0-logloss:0.09757	validation_1-logloss:0.17773
[78]	validation_0-logloss:0.09752	validation_1-logloss:0.17771
[79]	validation_0-logloss:0.09743	validation_1-logloss:0.17770
[80]	validation_0-logloss:0.09735	validation_1-logloss:0.17765
[81]	validation_0-logloss:0.09725	validation_1-logloss:0.17762
[82]	validation_0-logloss:0.09719	validation_1-logloss:0.17762
[83]	validation_0-logloss:0.09708	validation_1-logloss:0.17762
[84]	validation_0-logloss:0.09697	validation_1-logloss:0.17760
[85]	validation_0-logloss:0.09692	validation_1-logloss:0.17758
[86]	validation_0-logloss:0.09681	validation_1-logloss:0.17758
[87]	validation_0-logloss:0.09675	validation_1-logloss:0.17755
[88]	validation_0-logloss:0.09669	validation_1-logloss:0.17758
[89]	validation_0-logloss:0.09661	validation_1-logloss:0.17760
[90]	validation_0-logloss:0.09644	validation_1-logloss:0.17759
[91]	validation_0-logloss:0.09636	validation_1-logloss:0.17760
[92]	validation_0-logloss:0.09627	validation_1-logloss:0.17761
[93]	validation_0-logloss:0.09617	validation_1-logloss:0.17763
[94]	validation_0-logloss:0.09609	validation_1-logloss:0.17768
[95]	validation_0-logloss:0.09602	validation_1-logloss:0.17768
[96]	validation_0-logloss:0.09595	validation_1-logloss:0.17764
[97]	validation_0-logloss:0.09587	validation_1-logloss:0.17763
[98]	validation_0-logloss:0.09583	validation_1-logloss:0.17761
[99]	validation_0-logloss:0.09572	validation_1-logloss:0.17760
[100]	validation_0-logloss:0.09567	validation_1-logloss:0.17758
[101]	validation_0-logloss:0.09562	validation_1-logloss:0.17756
[102]	validation_0-logloss:0.09553	validation_1-logloss:0.17754
[103]	validation_0-logloss:0.09546	validation_1-logloss:0.17752
[104]	validation_0-logloss:0.09534	validation_1-logloss:0.17750
[105]	validation_0-logloss:0.09522	validation_1-logloss:0.17747
[106]	validation_0-logloss:0.09515	validation_1-logloss:0.17744
[107]	validation_0-logloss:0.09508	validation_1-logloss:0.17744
[108]	validation_0-logloss:0.09500	validation_1-logloss:0.17746
[109]	validation_0-logloss:0.09494	validation_1-logloss:0.17746
[110]	validation_0-logloss:0.09486	validation_1-logloss:0.17746
[111]	validation_0-logloss:0.09478	validation_1-logloss:0.17745
[112]	validation_0-logloss:0.09470	validation_1-logloss:0.17744
[113]	validation_0-logloss:0.09465	validation_1-logloss:0.17744
[114]	validation_0-logloss:0.09453	validation_1-logloss:0.17746
[115]	validation_0-logloss:0.09447	validation_1-logloss:0.17744
[116]	validation_0-logloss:0.09442	validation_1-logloss:0.17745
[117]	validation_0-logloss:0.09434	validation_1-logloss:0.17740
[118]	validation_0-logloss:0.09428	validation_1-logloss:0.17741
[119]	validation_0-logloss:0.09420	validation_1-logloss:0.17739
[120]	validation_0-logloss:0.09413	validation_1-logloss:0.17737
[121]	validation_0-logloss:0.09395	validation_1-logloss:0.17734
[122]	validation_0-logloss:0.09392	validation_1-logloss:0.17733
[123]	validation_0-logloss:0.09385	validation_1-logloss:0.17731
[124]	validation_0-logloss:0.09380	validation_1-logloss:0.17731
[125]	validation_0-logloss:0.09369	validation_1-logloss:0.17731
[126]	validation_0-logloss:0.09363	validation_1-logloss:0.17730
[127]	validation_0-logloss:0.09356	validation_1-logloss:0.17730
[128]	validation_0-logloss:0.09350	validation_1-logloss:0.17732
[129]	validation_0-logloss:0.09340	validation_1-logloss:0.17732
[130]	validation_0-logloss:0.09327	validation_1-logloss:0.17736
[131]	validation_0-logloss:0.09322	validation_1-logloss:0.17735
[132]	validation_0-logloss:0.09312	validation_1-logloss:0.17730
[133]	validation_0-logloss:0.09294	validation_1-logloss:0.17727
[134]	validation_0-logloss:0.09284	validation_1-logloss:0.17731
[135]	validation_0-logloss:0.09277	validation_1-logloss:0.17729
[136]	validation_0-logloss:0.09271	validation_1-logloss:0.17727
[137]	validation_0-logloss:0.09267	validation_1-logloss:0.17725
[138]	validation_0-logloss:0.09262	validation_1-logloss:0.17724
[139]	validation_0-logloss:0.09255	validation_1-logloss:0.17723
[140]	validation_0-logloss:0.09249	validation_1-logloss:0.17725
[141]	validation_0-logloss:0.09243	validation_1-logloss:0.17722
[142]	validation_0-logloss:0.09236	validation_1-logloss:0.17721
[143]	validation_0-logloss:0.09229	validation_1-logloss:0.17722
[144]	validation_0-logloss:0.09223	validation_1-logloss:0.17720
[145]	validation_0-logloss:0.09217	validation_1-logloss:0.17720
[146]	validation_0-logloss:0.09208	validation_1-logloss:0.17720
[147]	validation_0-logloss:0.09200	validation_1-logloss:0.17718
[148]	validation_0-logloss:0.09194	validation_1-logloss:0.17718
[149]	validation_0-logloss:0.09186	validation_1-logloss:0.17713
[150]	validation_0-logloss:0.09177	validation_1-logloss:0.17716
[151]	validation_0-logloss:0.09169	validation_1-logloss:0.17713
[152]	validation_0-logloss:0.09162	validation_1-logloss:0.17714
[153]	validation_0-logloss:0.09152	validation_1-logloss:0.17713
[154]	validation_0-logloss:0.09144	validation_1-logloss:0.17714
[155]	validation_0-logloss:0.09135	validation_1-logloss:0.17715
[156]	validation_0-logloss:0.09119	validation_1-logloss:0.17718
[157]	validation_0-logloss:0.09109	validation_1-logloss:0.17712
[158]	validation_0-logloss:0.09103	validation_1-logloss:0.17708
[159]	validation_0-logloss:0.09095	validation_1-logloss:0.17707
[160]	validation_0-logloss:0.09088	validation_1-logloss:0.17706
[161]	validation_0-logloss:0.09082	validation_1-logloss:0.17705
[162]	validation_0-logloss:0.09074	validation_1-logloss:0.17704
[163]	validation_0-logloss:0.09066	validation_1-logloss:0.17703
[164]	validation_0-logloss:0.09058	validation_1-logloss:0.17697
[165]	validation_0-logloss:0.09051	validation_1-logloss:0.17698
[166]	validation_0-logloss:0.09044	validation_1-logloss:0.17695
[167]	validation_0-logloss:0.09034	validation_1-logloss:0.17691
[168]	validation_0-logloss:0.09024	validation_1-logloss:0.17689
[169]	validation_0-logloss:0.09018	validation_1-logloss:0.17690
[170]	validation_0-logloss:0.09010	validation_1-logloss:0.17690
[171]	validation_0-logloss:0.09007	validation_1-logloss:0.17690
[172]	validation_0-logloss:0.09002	validation_1-logloss:0.17692
[173]	validation_0-logloss:0.08992	validation_1-logloss:0.17690
[174]	validation_0-logloss:0.08986	validation_1-logloss:0.17692
[175]	validation_0-logloss:0.08980	validation_1-logloss:0.17691
[176]	validation_0-logloss:0.08974	validation_1-logloss:0.17692
[177]	validation_0-logloss:0.08968	validation_1-logloss:0.17688
[178]	validation_0-logloss:0.08962	validation_1-logloss:0.17688
[179]	validation_0-logloss:0.08949	validation_1-logloss:0.17688
[180]	validation_0-logloss:0.08942	validation_1-logloss:0.17686
[181]	validation_0-logloss:0.08936	validation_1-logloss:0.17685
[182]	validation_0-logloss:0.08931	validation_1-logloss:0.17685
[183]	validation_0-logloss:0.08926	validation_1-logloss:0.17683
[184]	validation_0-logloss:0.08923	validation_1-logloss:0.17682
[185]	validation_0-logloss:0.08918	validation_1-logloss:0.17684
[186]	validation_0-logloss:0.08909	validation_1-logloss:0.17687
[187]	validation_0-logloss:0.08903	validation_1-logloss:0.17686
[188]	validation_0-logloss:0.08897	validation_1-logloss:0.17685
[189]	validation_0-logloss:0.08890	validation_1-logloss:0.17686
[190]	validation_0-logloss:0.08882	validation_1-logloss:0.17683
[191]	validation_0-logloss:0.08877	validation_1-logloss:0.17684
[192]	validation_0-logloss:0.08867	validation_1-logloss:0.17687
[193]	validation_0-logloss:0.08862	validation_1-logloss:0.17687
[194]	validation_0-logloss:0.08855	validation_1-logloss:0.17686
[195]	validation_0-logloss:0.08850	validation_1-logloss:0.17684
[196]	validation_0-logloss:0.08845	validation_1-logloss:0.17683
[197]	validation_0-logloss:0.08840	validation_1-logloss:0.17680
[198]	validation_0-logloss:0.08834	validation_1-logloss:0.17681
[199]	validation_0-logloss:0.08829	validation_1-logloss:0.17680

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy='multi_output_tree',
              n_estimators=200, n_jobs=None, num_parallel_tree=None, ...)

In [82]:
model5 = xgb.XGBClassifier(
    tree_method="hist", 
    multi_strategy="multi_output_tree",
    objective="binary:logistic", # Vẫn dùng binary vì mỗi cột là 1 xác suất ĐÚNG/SAI độc lập
    n_estimators=300,            # Số cây
    learning_rate=0.03,
    max_depth=6,
    random_state=42,

)
model5.fit(
    X_train, Y_train,
    xgb_model=model4.get_booster(),
    eval_set=[(X_train, Y_train), (X_val, Y_val)], # xem cả train và val
    verbose=True # True = in ra mỗi vòng, verbose=10 = in mỗi 10 vòng
)

[0]	validation_0-logloss:0.08827	validation_1-logloss:0.17681
[1]	validation_0-logloss:0.08825	validation_1-logloss:0.17681
[2]	validation_0-logloss:0.08823	validation_1-logloss:0.17679
[3]	validation_0-logloss:0.08821	validation_1-logloss:0.17678
[4]	validation_0-logloss:0.08819	validation_1-logloss:0.17678
[5]	validation_0-logloss:0.08817	validation_1-logloss:0.17677
[6]	validation_0-logloss:0.08815	validation_1-logloss:0.17677
[7]	validation_0-logloss:0.08813	validation_1-logloss:0.17677
[8]	validation_0-logloss:0.08812	validation_1-logloss:0.17677
[9]	validation_0-logloss:0.08810	validation_1-logloss:0.17676
[10]	validation_0-logloss:0.08806	validation_1-logloss:0.17676
[11]	validation_0-logloss:0.08804	validation_1-logloss:0.17675
[12]	validation_0-logloss:0.08802	validation_1-logloss:0.17675
[13]	validation_0-logloss:0.08801	validation_1-logloss:0.17675
[14]	validation_0-logloss:0.08798	validation_1-logloss:0.17675
[15]	validation_0-logloss:0.08797	validation_1-logloss:0.17675
[16]	validation_0-logloss:0.08795	validation_1-logloss:0.17675
[17]	validation_0-logloss:0.08793	validation_1-logloss:0.17676
[18]	validation_0-logloss:0.08791	validation_1-logloss:0.17676
[19]	validation_0-logloss:0.08788	validation_1-logloss:0.17675
[20]	validation_0-logloss:0.08786	validation_1-logloss:0.17674
[21]	validation_0-logloss:0.08784	validation_1-logloss:0.17674
[22]	validation_0-logloss:0.08782	validation_1-logloss:0.17673
[23]	validation_0-logloss:0.08781	validation_1-logloss:0.17673
[24]	validation_0-logloss:0.08778	validation_1-logloss:0.17672
[25]	validation_0-logloss:0.08776	validation_1-logloss:0.17672
[26]	validation_0-logloss:0.08774	validation_1-logloss:0.17671
[27]	validation_0-logloss:0.08770	validation_1-logloss:0.17671
[28]	validation_0-logloss:0.08768	validation_1-logloss:0.17671
[29]	validation_0-logloss:0.08767	validation_1-logloss:0.17672
[30]	validation_0-logloss:0.08765	validation_1-logloss:0.17671
[31]	validation_0-logloss:0.08763	validation_1-logloss:0.17671
[32]	validation_0-logloss:0.08761	validation_1-logloss:0.17670
[33]	validation_0-logloss:0.08759	validation_1-logloss:0.17670
[34]	validation_0-logloss:0.08758	validation_1-logloss:0.17670
[35]	validation_0-logloss:0.08756	validation_1-logloss:0.17670
[36]	validation_0-logloss:0.08754	validation_1-logloss:0.17670
[37]	validation_0-logloss:0.08752	validation_1-logloss:0.17671
[38]	validation_0-logloss:0.08750	validation_1-logloss:0.17671
[39]	validation_0-logloss:0.08748	validation_1-logloss:0.17671
[40]	validation_0-logloss:0.08746	validation_1-logloss:0.17670
[41]	validation_0-logloss:0.08744	validation_1-logloss:0.17670
[42]	validation_0-logloss:0.08742	validation_1-logloss:0.17670
[43]	validation_0-logloss:0.08740	validation_1-logloss:0.17670
[44]	validation_0-logloss:0.08739	validation_1-logloss:0.17669
[45]	validation_0-logloss:0.08737	validation_1-logloss:0.17670
[46]	validation_0-logloss:0.08735	validation_1-logloss:0.17670
[47]	validation_0-logloss:0.08733	validation_1-logloss:0.17670
[48]	validation_0-logloss:0.08731	validation_1-logloss:0.17671
[49]	validation_0-logloss:0.08730	validation_1-logloss:0.17671
[50]	validation_0-logloss:0.08728	validation_1-logloss:0.17669
[51]	validation_0-logloss:0.08725	validation_1-logloss:0.17669
[52]	validation_0-logloss:0.08723	validation_1-logloss:0.17668
[53]	validation_0-logloss:0.08722	validation_1-logloss:0.17669
[54]	validation_0-logloss:0.08720	validation_1-logloss:0.17669
[55]	validation_0-logloss:0.08718	validation_1-logloss:0.17668
[56]	validation_0-logloss:0.08717	validation_1-logloss:0.17667
[57]	validation_0-logloss:0.08716	validation_1-logloss:0.17667
[58]	validation_0-logloss:0.08714	validation_1-logloss:0.17667
[59]	validation_0-logloss:0.08713	validation_1-logloss:0.17666
[60]	validation_0-logloss:0.08709	validation_1-logloss:0.17666
[61]	validation_0-logloss:0.08707	validation_1-logloss:0.17665
[62]	validation_0-logloss:0.08704	validation_1-logloss:0.17666
[63]	validation_0-logloss:0.08702	validation_1-logloss:0.17666
[64]	validation_0-logloss:0.08700	validation_1-logloss:0.17666
[65]	validation_0-logloss:0.08698	validation_1-logloss:0.17666
[66]	validation_0-logloss:0.08696	validation_1-logloss:0.17666
[67]	validation_0-logloss:0.08694	validation_1-logloss:0.17666
[68]	validation_0-logloss:0.08691	validation_1-logloss:0.17666
[69]	validation_0-logloss:0.08689	validation_1-logloss:0.17664
[70]	validation_0-logloss:0.08687	validation_1-logloss:0.17663
[71]	validation_0-logloss:0.08685	validation_1-logloss:0.17663
[72]	validation_0-logloss:0.08683	validation_1-logloss:0.17662
[73]	validation_0-logloss:0.08681	validation_1-logloss:0.17663
[74]	validation_0-logloss:0.08680	validation_1-logloss:0.17662
[75]	validation_0-logloss:0.08678	validation_1-logloss:0.17662
[76]	validation_0-logloss:0.08677	validation_1-logloss:0.17662
[77]	validation_0-logloss:0.08675	validation_1-logloss:0.17662
[78]	validation_0-logloss:0.08674	validation_1-logloss:0.17661
[79]	validation_0-logloss:0.08672	validation_1-logloss:0.17661
[80]	validation_0-logloss:0.08670	validation_1-logloss:0.17660
[81]	validation_0-logloss:0.08668	validation_1-logloss:0.17659
[82]	validation_0-logloss:0.08666	validation_1-logloss:0.17659
[83]	validation_0-logloss:0.08665	validation_1-logloss:0.17659
[84]	validation_0-logloss:0.08663	validation_1-logloss:0.17659
[85]	validation_0-logloss:0.08661	validation_1-logloss:0.17660
[86]	validation_0-logloss:0.08660	validation_1-logloss:0.17660
[87]	validation_0-logloss:0.08656	validation_1-logloss:0.17659
[88]	validation_0-logloss:0.08653	validation_1-logloss:0.17660
[89]	validation_0-logloss:0.08652	validation_1-logloss:0.17660
[90]	validation_0-logloss:0.08650	validation_1-logloss:0.17660
[91]	validation_0-logloss:0.08648	validation_1-logloss:0.17659
[92]	validation_0-logloss:0.08646	validation_1-logloss:0.17659
[93]	validation_0-logloss:0.08644	validation_1-logloss:0.17659
[94]	validation_0-logloss:0.08643	validation_1-logloss:0.17659
[95]	validation_0-logloss:0.08641	validation_1-logloss:0.17659
[96]	validation_0-logloss:0.08639	validation_1-logloss:0.17658
[97]	validation_0-logloss:0.08636	validation_1-logloss:0.17658
[98]	validation_0-logloss:0.08635	validation_1-logloss:0.17659
[99]	validation_0-logloss:0.08633	validation_1-logloss:0.17659
[100]	validation_0-logloss:0.08631	validation_1-logloss:0.17660
[101]	validation_0-logloss:0.08629	validation_1-logloss:0.17660
[102]	validation_0-logloss:0.08628	validation_1-logloss:0.17659
[103]	validation_0-logloss:0.08627	validation_1-logloss:0.17659
[104]	validation_0-logloss:0.08625	validation_1-logloss:0.17658
[105]	validation_0-logloss:0.08622	validation_1-logloss:0.17658
[106]	validation_0-logloss:0.08620	validation_1-logloss:0.17658
[107]	validation_0-logloss:0.08618	validation_1-logloss:0.17657
[108]	validation_0-logloss:0.08616	validation_1-logloss:0.17657
[109]	validation_0-logloss:0.08614	validation_1-logloss:0.17656
[110]	validation_0-logloss:0.08611	validation_1-logloss:0.17656
[111]	validation_0-logloss:0.08609	validation_1-logloss:0.17656
[112]	validation_0-logloss:0.08607	validation_1-logloss:0.17656
[113]	validation_0-logloss:0.08605	validation_1-logloss:0.17656
[114]	validation_0-logloss:0.08603	validation_1-logloss:0.17655
[115]	validation_0-logloss:0.08602	validation_1-logloss:0.17656
[116]	validation_0-logloss:0.08599	validation_1-logloss:0.17656
[117]	validation_0-logloss:0.08597	validation_1-logloss:0.17656
[118]	validation_0-logloss:0.08596	validation_1-logloss:0.17655
[119]	validation_0-logloss:0.08594	validation_1-logloss:0.17655
[120]	validation_0-logloss:0.08593	validation_1-logloss:0.17656
[121]	validation_0-logloss:0.08592	validation_1-logloss:0.17656
[122]	validation_0-logloss:0.08590	validation_1-logloss:0.17657
[123]	validation_0-logloss:0.08589	validation_1-logloss:0.17656
[124]	validation_0-logloss:0.08587	validation_1-logloss:0.17657
[125]	validation_0-logloss:0.08586	validation_1-logloss:0.17658
[126]	validation_0-logloss:0.08584	validation_1-logloss:0.17658
[127]	validation_0-logloss:0.08582	validation_1-logloss:0.17657
[128]	validation_0-logloss:0.08580	validation_1-logloss:0.17657
[129]	validation_0-logloss:0.08578	validation_1-logloss:0.17657
[130]	validation_0-logloss:0.08576	validation_1-logloss:0.17657
[131]	validation_0-logloss:0.08575	validation_1-logloss:0.17656
[132]	validation_0-logloss:0.08574	validation_1-logloss:0.17656
[133]	validation_0-logloss:0.08572	validation_1-logloss:0.17655
[134]	validation_0-logloss:0.08571	validation_1-logloss:0.17656
[135]	validation_0-logloss:0.08569	validation_1-logloss:0.17655
[136]	validation_0-logloss:0.08567	validation_1-logloss:0.17654
[137]	validation_0-logloss:0.08565	validation_1-logloss:0.17654
[138]	validation_0-logloss:0.08564	validation_1-logloss:0.17655
[139]	validation_0-logloss:0.08562	validation_1-logloss:0.17654
[140]	validation_0-logloss:0.08560	validation_1-logloss:0.17653
[141]	validation_0-logloss:0.08555	validation_1-logloss:0.17652
[142]	validation_0-logloss:0.08553	validation_1-logloss:0.17652
[143]	validation_0-logloss:0.08551	validation_1-logloss:0.17651
[144]	validation_0-logloss:0.08549	validation_1-logloss:0.17651
[145]	validation_0-logloss:0.08547	validation_1-logloss:0.17650
[146]	validation_0-logloss:0.08543	validation_1-logloss:0.17649
[147]	validation_0-logloss:0.08541	validation_1-logloss:0.17649
[148]	validation_0-logloss:0.08540	validation_1-logloss:0.17648
[149]	validation_0-logloss:0.08538	validation_1-logloss:0.17649
[150]	validation_0-logloss:0.08536	validation_1-logloss:0.17649
[151]	validation_0-logloss:0.08533	validation_1-logloss:0.17649
[152]	validation_0-logloss:0.08532	validation_1-logloss:0.17648
[153]	validation_0-logloss:0.08530	validation_1-logloss:0.17649
[154]	validation_0-logloss:0.08528	validation_1-logloss:0.17648
[155]	validation_0-logloss:0.08527	validation_1-logloss:0.17648
[156]	validation_0-logloss:0.08522	validation_1-logloss:0.17647
[157]	validation_0-logloss:0.08520	validation_1-logloss:0.17646
[158]	validation_0-logloss:0.08517	validation_1-logloss:0.17647
[159]	validation_0-logloss:0.08515	validation_1-logloss:0.17646
[160]	validation_0-logloss:0.08514	validation_1-logloss:0.17646
[161]	validation_0-logloss:0.08512	validation_1-logloss:0.17645
[162]	validation_0-logloss:0.08509	validation_1-logloss:0.17644
[163]	validation_0-logloss:0.08506	validation_1-logloss:0.17643
[164]	validation_0-logloss:0.08503	validation_1-logloss:0.17642
[165]	validation_0-logloss:0.08501	validation_1-logloss:0.17642
[166]	validation_0-logloss:0.08500	validation_1-logloss:0.17642
[167]	validation_0-logloss:0.08498	validation_1-logloss:0.17641
[168]	validation_0-logloss:0.08497	validation_1-logloss:0.17641
[169]	validation_0-logloss:0.08494	validation_1-logloss:0.17640
[170]	validation_0-logloss:0.08493	validation_1-logloss:0.17640
[171]	validation_0-logloss:0.08491	validation_1-logloss:0.17641
[172]	validation_0-logloss:0.08489	validation_1-logloss:0.17641
[173]	validation_0-logloss:0.08487	validation_1-logloss:0.17641
[174]	validation_0-logloss:0.08485	validation_1-logloss:0.17641
[175]	validation_0-logloss:0.08483	validation_1-logloss:0.17641
[176]	validation_0-logloss:0.08482	validation_1-logloss:0.17640
[177]	validation_0-logloss:0.08480	validation_1-logloss:0.17641
[178]	validation_0-logloss:0.08478	validation_1-logloss:0.17639
[179]	validation_0-logloss:0.08475	validation_1-logloss:0.17639
[180]	validation_0-logloss:0.08473	validation_1-logloss:0.17639
[181]	validation_0-logloss:0.08472	validation_1-logloss:0.17639
[182]	validation_0-logloss:0.08469	validation_1-logloss:0.17640
[183]	validation_0-logloss:0.08466	validation_1-logloss:0.17639
[184]	validation_0-logloss:0.08464	validation_1-logloss:0.17639
[185]	validation_0-logloss:0.08463	validation_1-logloss:0.17640
[186]	validation_0-logloss:0.08461	validation_1-logloss:0.17640
[187]	validation_0-logloss:0.08459	validation_1-logloss:0.17639
[188]	validation_0-logloss:0.08458	validation_1-logloss:0.17638
[189]	validation_0-logloss:0.08456	validation_1-logloss:0.17638
[190]	validation_0-logloss:0.08455	validation_1-logloss:0.17638
[191]	validation_0-logloss:0.08454	validation_1-logloss:0.17637
[192]	validation_0-logloss:0.08452	validation_1-logloss:0.17638
[193]	validation_0-logloss:0.08450	validation_1-logloss:0.17638
[194]	validation_0-logloss:0.08449	validation_1-logloss:0.17637
[195]	validation_0-logloss:0.08447	validation_1-logloss:0.17637
[196]	validation_0-logloss:0.08445	validation_1-logloss:0.17637
[197]	validation_0-logloss:0.08444	validation_1-logloss:0.17637
[198]	validation_0-logloss:0.08442	validation_1-logloss:0.17638
[199]	validation_0-logloss:0.08441	validation_1-logloss:0.17638
[200]	validation_0-logloss:0.08440	validation_1-logloss:0.17637
[201]	validation_0-logloss:0.08438	validation_1-logloss:0.17637
[202]	validation_0-logloss:0.08436	validation_1-logloss:0.17637
[203]	validation_0-logloss:0.08434	validation_1-logloss:0.17638
[204]	validation_0-logloss:0.08432	validation_1-logloss:0.17638
[205]	validation_0-logloss:0.08431	validation_1-logloss:0.17637
[206]	validation_0-logloss:0.08430	validation_1-logloss:0.17636
[207]	validation_0-logloss:0.08428	validation_1-logloss:0.17637
[208]	validation_0-logloss:0.08427	validation_1-logloss:0.17637
[209]	validation_0-logloss:0.08426	validation_1-logloss:0.17637
[210]	validation_0-logloss:0.08425	validation_1-logloss:0.17637
[211]	validation_0-logloss:0.08423	validation_1-logloss:0.17637
[212]	validation_0-logloss:0.08421	validation_1-logloss:0.17637
[213]	validation_0-logloss:0.08420	validation_1-logloss:0.17636
[214]	validation_0-logloss:0.08418	validation_1-logloss:0.17636
[215]	validation_0-logloss:0.08415	validation_1-logloss:0.17637
[216]	validation_0-logloss:0.08413	validation_1-logloss:0.17637
[217]	validation_0-logloss:0.08411	validation_1-logloss:0.17636
[218]	validation_0-logloss:0.08410	validation_1-logloss:0.17636
[219]	validation_0-logloss:0.08408	validation_1-logloss:0.17637
[220]	validation_0-logloss:0.08407	validation_1-logloss:0.17637
[221]	validation_0-logloss:0.08405	validation_1-logloss:0.17636
[222]	validation_0-logloss:0.08403	validation_1-logloss:0.17636
[223]	validation_0-logloss:0.08402	validation_1-logloss:0.17636
[224]	validation_0-logloss:0.08401	validation_1-logloss:0.17636
[225]	validation_0-logloss:0.08399	validation_1-logloss:0.17636
[226]	validation_0-logloss:0.08397	validation_1-logloss:0.17637
[227]	validation_0-logloss:0.08395	validation_1-logloss:0.17636
[228]	validation_0-logloss:0.08393	validation_1-logloss:0.17637
[229]	validation_0-logloss:0.08389	validation_1-logloss:0.17638
[230]	validation_0-logloss:0.08388	validation_1-logloss:0.17638
[231]	validation_0-logloss:0.08387	validation_1-logloss:0.17637
[232]	validation_0-logloss:0.08386	validation_1-logloss:0.17638
[233]	validation_0-logloss:0.08384	validation_1-logloss:0.17638
[234]	validation_0-logloss:0.08382	validation_1-logloss:0.17639
[235]	validation_0-logloss:0.08380	validation_1-logloss:0.17638
[236]	validation_0-logloss:0.08376	validation_1-logloss:0.17638
[237]	validation_0-logloss:0.08374	validation_1-logloss:0.17638
[238]	validation_0-logloss:0.08371	validation_1-logloss:0.17637
[239]	validation_0-logloss:0.08370	validation_1-logloss:0.17637
[240]	validation_0-logloss:0.08368	validation_1-logloss:0.17637
[241]	validation_0-logloss:0.08367	validation_1-logloss:0.17637
[242]	validation_0-logloss:0.08366	validation_1-logloss:0.17637
[243]	validation_0-logloss:0.08364	validation_1-logloss:0.17637
[244]	validation_0-logloss:0.08362	validation_1-logloss:0.17637
[245]	validation_0-logloss:0.08360	validation_1-logloss:0.17637
[246]	validation_0-logloss:0.08358	validation_1-logloss:0.17636
[247]	validation_0-logloss:0.08357	validation_1-logloss:0.17636
[248]	validation_0-logloss:0.08355	validation_1-logloss:0.17636
[249]	validation_0-logloss:0.08353	validation_1-logloss:0.17636
[250]	validation_0-logloss:0.08352	validation_1-logloss:0.17636
[251]	validation_0-logloss:0.08350	validation_1-logloss:0.17636
[252]	validation_0-logloss:0.08349	validation_1-logloss:0.17635
[253]	validation_0-logloss:0.08347	validation_1-logloss:0.17637
[254]	validation_0-logloss:0.08346	validation_1-logloss:0.17636
[255]	validation_0-logloss:0.08344	validation_1-logloss:0.17635
[256]	validation_0-logloss:0.08342	validation_1-logloss:0.17635
[257]	validation_0-logloss:0.08340	validation_1-logloss:0.17635
[258]	validation_0-logloss:0.08339	validation_1-logloss:0.17634
[259]	validation_0-logloss:0.08336	validation_1-logloss:0.17633
[260]	validation_0-logloss:0.08334	validation_1-logloss:0.17634
[261]	validation_0-logloss:0.08333	validation_1-logloss:0.17634
[262]	validation_0-logloss:0.08332	validation_1-logloss:0.17634
[263]	validation_0-logloss:0.08330	validation_1-logloss:0.17634
[264]	validation_0-logloss:0.08328	validation_1-logloss:0.17634
[265]	validation_0-logloss:0.08326	validation_1-logloss:0.17634
[266]	validation_0-logloss:0.08325	validation_1-logloss:0.17634
[267]	validation_0-logloss:0.08323	validation_1-logloss:0.17634
[268]	validation_0-logloss:0.08321	validation_1-logloss:0.17635
[269]	validation_0-logloss:0.08318	validation_1-logloss:0.17634
[270]	validation_0-logloss:0.08317	validation_1-logloss:0.17634
[271]	validation_0-logloss:0.08315	validation_1-logloss:0.17634
[272]	validation_0-logloss:0.08314	validation_1-logloss:0.17634
[273]	validation_0-logloss:0.08311	validation_1-logloss:0.17633
[274]	validation_0-logloss:0.08310	validation_1-logloss:0.17633
[275]	validation_0-logloss:0.08308	validation_1-logloss:0.17633
[276]	validation_0-logloss:0.08307	validation_1-logloss:0.17632
[277]	validation_0-logloss:0.08305	validation_1-logloss:0.17631
[278]	validation_0-logloss:0.08303	validation_1-logloss:0.17631
[279]	validation_0-logloss:0.08302	validation_1-logloss:0.17631
[280]	validation_0-logloss:0.08300	validation_1-logloss:0.17631
[281]	validation_0-logloss:0.08299	validation_1-logloss:0.17631
[282]	validation_0-logloss:0.08297	validation_1-logloss:0.17632
[283]	validation_0-logloss:0.08295	validation_1-logloss:0.17632
[284]	validation_0-logloss:0.08294	validation_1-logloss:0.17632
[285]	validation_0-logloss:0.08291	validation_1-logloss:0.17632
[286]	validation_0-logloss:0.08289	validation_1-logloss:0.17631
[287]	validation_0-logloss:0.08287	validation_1-logloss:0.17631
[288]	validation_0-logloss:0.08285	validation_1-logloss:0.17630
[289]	validation_0-logloss:0.08283	validation_1-logloss:0.17630
[290]	validation_0-logloss:0.08282	validation_1-logloss:0.17630
[291]	validation_0-logloss:0.08279	validation_1-logloss:0.17630
[292]	validation_0-logloss:0.08278	validation_1-logloss:0.17630
[293]	validation_0-logloss:0.08277	validation_1-logloss:0.17630
[294]	validation_0-logloss:0.08275	validation_1-logloss:0.17631
[295]	validation_0-logloss:0.08274	validation_1-logloss:0.17630
[296]	validation_0-logloss:0.08272	validation_1-logloss:0.17630
[297]	validation_0-logloss:0.08271	validation_1-logloss:0.17630
[298]	validation_0-logloss:0.08270	validation_1-logloss:0.17630
[299]	validation_0-logloss:0.08269	validation_1-logloss:0.17629

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.03, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy='multi_output_tree',
              n_estimators=300, n_jobs=None, num_parallel_tree=None, ...)

In [29]:
model=xgb.XGBClassifier()
model.load_model("model.json")

In [25]:
model5=xgb.XGBClassifier()
model5.load_model("model5.json")

In [26]:
print(model5.get_booster().num_boosted_rounds())

1000

In [143]:
from numpy import average
from sklearn.metrics import jaccard_score, f1_score
proba=model5.predict_proba(X_val)
Y_pred = (proba >= 0.5).astype(int)

# nếu cả 4 đều < 0.5 thì lấy thằng lớn nhất
# all_zero = Y_pred.sum(axis=1) == 0
# Y_pred[all_zero, proba[all_zero].argmax(axis=1)] = 1
# Y_pred=model5.predict(X_test)
print((Y_val == Y_pred).mean(axis=0))
f1_score(Y_val,Y_pred,average="samples")

[0.91661883 0.92896096 0.95752009 0.92192882]

0.8631116396041769

In [144]:
model.save_model("model.json")
model2.save_model("model2.json")
model3.save_model("model3.json")
model4.save_model("model4.json")
model5.save_model("model5.json")

In [57]:
Y_pred=model.predict(X_train)

In [58]:
Y_train

array([[0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       ...,
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0]], shape=(32519, 4))

In [59]:
Y_pred

array([[0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       ...,
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.]], shape=(32519, 4))

In [24]:
text = """Let $\\mathbb{N}$ denote the set of positive integers. A function $f\\colon\\mathbb{N}\\to\\mathbb{N}$ is said to be bonza if
\\[
f(a)\\mid b^a-f(b)^{f(a)}
\\]for all positive integers $a$ and $b$.

Determine the smallest real constant $c$ such that $f(n)\\leqslant cn$ for all bonza functions $f$ and all positive integers $n$."""
text2="This is a problem proposed by me"

In [ ]:
model=xgb.XGBClassifier()
model.load_model("model5.json")
inp=tfidf.transform(pd.Series([sp.encode(text)]).apply(lambda ids: " ".join(map(str, ids))))
model.predict_proba(inp)

array([[0.8606497 , 0.01337123, 0.00381078, 0.2882299 ]], dtype=float32)

In [43]:
X

thread_id
2           215 3 427 7916 81 6 332 7929 35 3 7970 7916 22...
3           4808 232 149 275 29 264 387 7924 7937 280 94 9...
5           320 79 7929 7951 101 7886 35 9 439 426 7948 79...
9           622 6 7885 471 3 7914 8 705 45 7916 905 2727 2...
72          266 2315 31 9 927 31 6 2166 3058 3 723 3147 79...
                                  ...
36238654    215 3 7912 7929 24 7929 18 7916 81 9 3551 31 3...
36238689    1022 170 1892 38 1023 9 733 98 170 566 362 3 7...
36238706    1782 22 3 7967 8 705 147 7916 7909 0 112 1687 ...
36238733    533 29 1689 38 156 1611 68 2514 256 42 1835 38...
36238754    622 332 3 427 48 3 311 138 217 7958 768 33 629...
Name: text, Length: 46456, dtype: str

In [51]:
Y_test

array([[0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       ...,
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1]], shape=(6969, 4))

In [55]:
Y_pred=model.predict(X_test)

In [ ]:
import numpy as np
from sklearn.metrics import jaccard_score, f1_score, precision_score, recall_score

def compute_metrics_from_arrays(X_test, Y_test):
    probs = 1 / (1 + np.exp(-X_test))
    preds = (probs >= 0.5).astype(int)
    labels = Y_test.astype(int)

    label_acc = np.mean(preds == labels, axis=0)

    jaccard_samples = jaccard_score(labels, preds, average="samples", zero_division=0)
    f1_micro = f1_score(labels, preds, average="micro", zero_division=0)
    f1_macro = f1_score(labels, preds, average="macro", zero_division=0)
    precision_micro = precision_score(labels, preds, average="micro", zero_division=0)
    recall_micro = recall_score(labels, preds, average="micro", zero_division=0)

    return {
        **{f"acc_label_{i}": float(acc) for i, acc in enumerate(label_acc)},
        "jaccard_samples": float(jaccard_samples),
        "f1_micro": float(f1_micro),
        "f1_macro": float(f1_macro),
        "precision_micro": float(precision_micro),
        "recall_micro": float(recall_micro),
    }

results = compute_metrics_from_arrays(X_test, Y_test)
print(results)

In [94]:
X1_train, X1_test, Y1_train, Y1_test = train_test_split(
    X, Y, test_size=0.3, random_state=42
)
X1_val, X1_test, Y1_val, Y1_test = train_test_split(
    X1_test, Y1_test, test_size=0.5, random_state=42
)

In [95]:
Y1_test

array([[0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       ...,
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1]], shape=(6969, 4))

In [99]:
df_test=pd.concat([pd.DataFrame(model.predict_proba(X_test)),pd.DataFrame(Y1_test,columns=[4,5,6,7])],axis=1)
df_test.index=X1_test.index

In [100]:
df_test

                  0         1         2         3  4  5  6  7
thread_id
24870212   0.000214  0.000138  0.999941  0.000286  0  0  1  0
30027564   0.679235  0.038116  0.023292  0.311279  1  0  0  0
24036068   0.000555  0.000291  0.999845  0.000207  0  0  1  0
268382     0.995820  0.000852  0.008129  0.038256  1  0  0  0
17129840   0.010099  0.924488  0.533873  0.004257  0  1  0  0
...             ...       ...       ...       ... .. .. .. ..
20972908   0.004340  0.000910  0.998420  0.000737  0  0  1  0
32725963   0.994263  0.003344  0.004340  0.010674  1  0  0  0
31808676   0.043412  0.086676  0.851388  0.087543  0  0  1  0
1681336    0.002946  0.984556  0.141118  0.004631  0  1  0  0
12297993   0.137256  0.004760  0.007653  0.951245  0  0  0  1

[6969 rows x 8 columns]

In [105]:
df_test[(df_test[2]<0.5)&(df_test[6]>0.5)&(df_test[5]<0.5)]

                  0         1         2         3  4  5  6  7
thread_id
27322324   0.178750  0.498954  0.220463  0.050541  0  0  1  0
14232733   0.381589  0.308786  0.223594  0.067797  0  0  1  0
915985     0.981127  0.007104  0.051303  0.005583  1  0  1  0
1798808    0.850140  0.013793  0.047788  0.118162  0  0  1  0
1986739    0.007218  0.666553  0.250520  0.128052  0  0  1  1
...             ...       ...       ...       ... .. .. .. ..
26566078   0.065465  0.444110  0.397772  0.064235  0  0  1  0
34025490   0.177655  0.145327  0.305269  0.292270  0  0  1  0
26751815   0.368617  0.318282  0.420387  0.090187  0  0  1  0
3005109    0.713123  0.015525  0.040418  0.438284  1  0  1  0
364398     0.019712  0.037355  0.034051  0.980854  0  0  1  1

[132 rows x 8 columns]

In [92]:
pd.DataFrame(Y1_test)

      0  1  2  3
0     0  0  1  0
1     1  0  0  0
2     0  0  1  0
3     1  0  0  0
4     0  1  0  0
...  .. .. .. ..
6964  0  0  1  0
6965  1  0  0  0
6966  0  0  1  0
6967  0  1  0  0
6968  0  0  0  1

[6969 rows x 4 columns]

In [90]:
df_test=pd.concat([df_test,pd.DataFrame(Y1_test)])

In [91]:
df_test

                 0         1         2         3
24870212  0.000214  0.000138  0.999941  0.000286
30027564  0.679235  0.038116  0.023292  0.311279
24036068  0.000555  0.000291  0.999845  0.000207
268382    0.995820  0.000852  0.008129  0.038256
17129840  0.010099  0.924488  0.533873  0.004257
...            ...       ...       ...       ...
6964      0.000000  0.000000  1.000000  0.000000
6965      1.000000  0.000000  0.000000  0.000000
6966      0.000000  0.000000  1.000000  0.000000
6967      0.000000  1.000000  0.000000  0.000000
6968      0.000000  0.000000  0.000000  1.000000

[13938 rows x 4 columns]

In [82]:
X1_test.index[fn_indices].to_numpy()

array([ 3607075,  9260243, 25272386, 27322324, 14232733,   915985,
        1798808,  1986739, 17248374,   320036,  2410835,  1358647,
       34748622, 22074856, 10867453,  1034894, 26998986,  2624552,
       20689778,  3462682,  1393141, 22213912, 10949296,  3305723,
        6696361, 32694068, 36058879, 32996086, 26575038, 17150556,
       13252349,   506193, 10549143, 30306766,  2386963,   487376,
        1389512,  2650922,  1567158,  2644130,  2939865, 35324642,
       11100972,  2677579,  1341978,   456566,  2422840, 22152974,
        1124777, 19464937, 33582037, 14970566,  1999385,   466207,
       27720516, 31293779, 34074602,  3492744, 24681373,  5331164,
        5852495,  3269345, 12602514,  3041827,  3490345, 21040339,
        3584572,  2681123, 34104714,  3515251,  3425592, 19751495,
       21748540,   849671,  2260935, 22161304, 18349960,   337820,
         364402,  3076921,   849665,  1115387, 17195562,  1327713,
        2594748,   860103, 32810158, 23959314, 11119206,  1604458,
        2131289, 13044578, 32735123, 26750812,   364401, 22388409,
        1478225,   495334, 12753056,   925899,  2608359, 23151157,
         820983, 24181473, 12794653, 22541374,  7710504,  3590206,
        1143132,  2024539,  1928461, 34074828,  1205676,  1395616,
        2908445, 32670380,  1257633, 11118817, 14891456, 13240304,
       34286919,  2244717, 21749062, 32723581, 32261649, 33312677,
       26302884,  2068539, 11089380, 28018739,   116528,  2188641,
        1549988, 20755895,  1857105, 25836753, 19826681,  3612201,
         807110, 30996098,  1470110, 32653954,  2146761, 10163742,
       32789115, 32723527,   322981,   855845, 34299472, 12893698,
       30829455, 29869590, 30692827,  3634742, 10739429, 10172915,
       32748683, 20949489,  2025517, 14203579, 10050519,   220467,
       13547412,  3076122, 32796105, 25473443, 35948357, 26232839,
       17899271,  2410840, 27781622,  2224415,  1857321,   347432,
        3078509,   887049,  2325914,  2691199,  3572808,   134620,
       26566078, 34025490, 26751815,  3005109,   364398])

In [83]:
c=np.column_stack([X1_test.index[fn_indices].to_numpy(),model.predict_proba(X_test)[fn_indices]])